package org.arghyam.jalsoochak.message.service;

import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.arghyam.jalsoochak.message.dto.DailyReportKpis;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Renders the Daily Water Service Situation Report PDF (Apache PDFBox) for one officer.
 *
 * <p>The layout mirrors {@code JalSoochak Daily Water Service Situation Report.docx} for the
 * SECTION_OFFICER role (v1): header, Summary KPI table (Yesterday vs Previous Day + trend),
 * Reasons for No Water Supply, and Anomalous Submissions. Modelled on {@link EscalationPdfService}.</p>
 *
 * <p>The SUB_DIVISIONAL_OFFICER layout is not yet specified; until an SDO sample is provided it
 * reuses the same layout (see {@code app.daily-report.sdo-enabled} gating in the router).</p>
 */
@Service
@Slf4j
public class DailyReportPdfService {

    @Value("${daily-report.report.dir:${escalation.report.dir:/tmp/escalation-reports/}}")
    private String reportDir;

    @Value("${daily-report.dashboard-url:https://jalsoochak.jjmbrain.in/}")
    private String dashboardUrl;

    @Value("${daily-report.support-phone:}")
    private String supportPhone;

    private static final float MARGIN = 50f;
    private static final float LINE_HEIGHT = 16f;
    private static final float PAGE_HEIGHT = PDRectangle.A4.getHeight();
    private static final DateTimeFormatter ISO = DateTimeFormatter.ISO_LOCAL_DATE;
    private static final DateTimeFormatter DISPLAY = DateTimeFormatter.ofPattern("dd-MMM-yyyy");
    private static final DateTimeFormatter HEADER = DateTimeFormatter.ofPattern("dd MMMM yyyy");

    private static final Map<String, String> ANOMALY_LABELS = Map.ofEntries(
            Map.entry("1", "Unreadable Image"),
            Map.entry("2", "Manual Override"),
            Map.entry("3", "Consecutive Override (5 days)"),
            Map.entry("4", "Duplicate Image"),
            Map.entry("5", "Reading Less Than Previous"),
            Map.entry("6", "No Water Supply"),
            Map.entry("7", "Low Water Supply"),
            Map.entry("8", "Over Water Supply"),
            Map.entry("9", "No Submission"));

    private PDType1Font bold;
    private PDType1Font regular;

    /**
     * Generates the report PDF and returns the filename (not the full path).
     *
     * @param kpis            computed KPI payload from analytics-service
     * @param officerName     decrypted officer display name (resolved by the caller)
     * @param officerUserType SECTION_OFFICER | SUB_DIVISIONAL_OFFICER (drives the filename + layout)
     */
    public String generate(DailyReportKpis kpis, String officerName, String officerUserType) throws IOException {
        ensureReportDirExists();

        LocalDate reportDate = LocalDate.parse(kpis.getReportDate(), ISO);
        LocalDate previousDate = LocalDate.parse(kpis.getPreviousDate(), ISO);

        String safeRole = (officerUserType != null ? officerUserType : "OFFICER").replaceAll("[^A-Za-z0-9_\\-]", "_");
        String safeName = (officerName != null ? officerName : "Officer").replaceAll("[^a-zA-Z0-9_\\-]", "_");
        String filename = String.format("daily_report_%s_%s_%s.pdf", safeRole, safeName, reportDate);
        Path filePath = Paths.get(reportDir, filename);

        try (PDDocument doc = new PDDocument()) {
            bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);
            PDPageContentStream cs = new PDPageContentStream(doc, page);
            float y = PAGE_HEIGHT - MARGIN;

            // ---- Header ----
            y = text(cs, bold, 16, "Daily Water Service Situation Report", MARGIN, y);
            y -= 4;
            y = text(cs, regular, 11, "Officer: " + safe(officerName != null ? officerName : "Officer"), MARGIN, y);
            y = text(cs, regular, 11, "Date: " + reportDate.plusDays(1).format(HEADER), MARGIN, y);
            y = text(cs, regular, 11, "Reporting Period: 00:00 hrs - 23:59 hrs", MARGIN, y);
            y = text(cs, regular, 9,
                    "Generated by JalSoochak. Visit the JalSoochak Dashboard at " + dashboardUrl + " for more insights",
                    MARGIN, y);
            y -= LINE_HEIGHT;

            // ---- 1. Summary ----
            y = text(cs, bold, 13, "1. Summary", MARGIN, y);
            y -= 4;
            String colY = "Yesterday (" + reportDate.format(DISPLAY) + ")";
            String colP = "Previous Day (" + previousDate.format(DISPLAY) + ")";
            float[] cols = {MARGIN, MARGIN + 220, MARGIN + 330, MARGIN + 445};
            y = tableHeader(cs, y, cols, "KPI", colY, colP, "Trend");

            DailyReportKpis.DayKpis yd = kpis.getYesterday();
            DailyReportKpis.DayKpis pd = kpis.getPreviousDay();
            y = kpiRow(cs, y, cols, "Total Schemes", kpis.getTotalSchemes(), kpis.getTotalSchemes());
            y = kpiRow(cs, y, cols, "Schemes Supplying Water", yd.getSchemesSupplying(), pd.getSchemesSupplying());
            y = kpiRow(cs, y, cols, "Schemes Not Supplying Water", yd.getSchemesNotSupplying(), pd.getSchemesNotSupplying());
            y = kpiRowD(cs, y, cols, "Average LPCD", yd.getAvgLpcd(), pd.getAvgLpcd(), "");
            y = kpiRowD(cs, y, cols, "Average MLD", yd.getAvgMld(), pd.getAvgMld(), "");
            y = kpiRowD(cs, y, cols, "Regular Supply (%) past 1 week", yd.getRegularSupplyPctWeek(), pd.getRegularSupplyPctWeek(), "%");
            y = kpiRowD(cs, y, cols, "Reading Submission (%)", yd.getReadingSubmissionPct(), pd.getReadingSubmissionPct(), "%");
            y = kpiRow(cs, y, cols, "Anomalous Submissions", yd.getAnomalousCount(), pd.getAnomalousCount());
            y -= LINE_HEIGHT;

            // ---- 3. Reasons for No Water Supply ----
            // The v1 report (Summary + Reasons + Anomalies) fits a single A4 page for realistic
            // data volumes (outage reasons and anomaly types are each bounded to a small set).
            y = text(cs, bold, 13, "3. Reasons for No Water Supply", MARGIN, y);
            y -= 4;
            float[] rcols = {MARGIN, MARGIN + 360};
            y = tableHeader(cs, y, rcols, "Reason", "Count", null, null);
            List<DailyReportKpis.ReasonCount> reasons = kpis.getReasonsForNoSupply();
            if (reasons == null || reasons.isEmpty()) {
                y = twoCol(cs, y, rcols, "No outages reported", "0");
            } else {
                for (DailyReportKpis.ReasonCount r : reasons) {
                    y = twoCol(cs, y, rcols, prettifyReason(r.getReason()), String.valueOf(r.getCount()));
                }
            }
            y -= LINE_HEIGHT;

            // ---- 4. Anomalous Submissions ----
            y = text(cs, bold, 13, "4. Anomalous Submissions", MARGIN, y);
            y -= 4;
            float[] acols = {MARGIN, MARGIN + 360};
            y = tableHeader(cs, y, acols, "Type", "Count", null, null);
            List<DailyReportKpis.TypeCount> anomalies = kpis.getAnomaliesByType();
            if (anomalies == null || anomalies.isEmpty()) {
                y = twoCol(cs, y, acols, "No anomalies", "0");
            } else {
                for (DailyReportKpis.TypeCount t : anomalies) {
                    y = twoCol(cs, y, acols, anomalyLabel(t.getType()), String.valueOf(t.getCount()));
                }
            }
            y -= LINE_HEIGHT;

            // ---- Footer ----
            if (supportPhone != null && !supportPhone.isBlank()) {
                text(cs, regular, 8,
                        "* If you think you received this message by mistake, please reach out to " + supportPhone,
                        MARGIN, y);
            }

            cs.close();
            doc.save(filePath.toFile());
        }

        log.info("[DailyReportPdf] Saved report to {}", filePath);
        return filename;
    }

    // ---- table / text helpers -------------------------------------------

    private float tableHeader(PDPageContentStream cs, float y, float[] cols,
                              String c0, String c1, String c2, String c3) throws IOException {
        cell(cs, bold, 10, c0, cols[0], y);
        if (c1 != null) cell(cs, bold, 10, c1, cols[1], y);
        if (c2 != null) cell(cs, bold, 10, c2, cols[2], y);
        if (c3 != null) cell(cs, bold, 10, c3, cols[3], y);
        return y - LINE_HEIGHT;
    }

    private float kpiRow(PDPageContentStream cs, float y, float[] cols, String label, int yVal, int pVal) throws IOException {
        cell(cs, regular, 10, label, cols[0], y);
        cell(cs, regular, 10, String.valueOf(yVal), cols[1], y);
        cell(cs, regular, 10, String.valueOf(pVal), cols[2], y);
        cell(cs, regular, 10, trend(yVal - pVal, ""), cols[3], y);
        return y - LINE_HEIGHT;
    }

    private float kpiRowD(PDPageContentStream cs, float y, float[] cols, String label,
                          double yVal, double pVal, String suffix) throws IOException {
        cell(cs, regular, 10, label, cols[0], y);
        cell(cs, regular, 10, fmt(yVal) + suffix, cols[1], y);
        cell(cs, regular, 10, fmt(pVal) + suffix, cols[2], y);
        cell(cs, regular, 10, trendD(yVal - pVal, suffix), cols[3], y);
        return y - LINE_HEIGHT;
    }

    private float twoCol(PDPageContentStream cs, float y, float[] cols, String c0, String c1) throws IOException {
        cell(cs, regular, 10, c0, cols[0], y);
        cell(cs, regular, 10, c1, cols[1], y);
        return y - LINE_HEIGHT;
    }

    private float text(PDPageContentStream cs, PDType1Font font, float size, String s, float x, float y) throws IOException {
        cell(cs, font, size, s, x, y);
        return y - LINE_HEIGHT;
    }

    private void cell(PDPageContentStream cs, PDType1Font font, float size, String s, float x, float y) throws IOException {
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(x, y);
        cs.showText(safe(s));
        cs.endText();
    }

    /** Signed-delta trend text — ASCII only to stay within Helvetica/WinAnsi encoding. */
    private String trend(int delta, String suffix) {
        if (delta == 0) return "0";
        return (delta > 0 ? "+" : "") + delta + suffix;
    }

    private String trendD(double delta, String suffix) {
        if (Math.abs(delta) < 0.05) return "0";
        return (delta > 0 ? "+" : "") + fmt(delta) + suffix;
    }

    private String fmt(double v) {
        return (v == Math.rint(v)) ? String.valueOf((long) v) : String.valueOf(v);
    }

    private String anomalyLabel(String type) {
        return ANOMALY_LABELS.getOrDefault(type, "Type " + type);
    }

    private String prettifyReason(String reason) {
        if (reason == null || reason.isBlank()) return "Unknown";
        String r = reason.trim();
        // Prettify config-style keys (SNAKE_CASE / lower_case) into Title Case words.
        if (r.matches("\\w+") && (r.contains("_") || r.equals(r.toUpperCase()) || r.equals(r.toLowerCase()))) {
            String[] parts = r.toLowerCase().split("_");
            StringBuilder sb = new StringBuilder();
            for (String p : parts) {
                if (p.isEmpty()) continue;
                sb.append(Character.toUpperCase(p.charAt(0))).append(p.substring(1)).append(' ');
            }
            return sb.toString().trim();
        }
        return r;
    }

    /** Strips characters outside Latin-1 so PDFBox's Standard-14 fonts never throw on encoding. */
    private String safe(String s) {
        if (s == null) return "";
        StringBuilder sb = new StringBuilder(s.length());
        for (char c : s.toCharArray()) {
            sb.append(c >= 32 && c <= 255 ? c : '?');
        }
        return sb.toString();
    }

    private void ensureReportDirExists() throws IOException {
        Path dir = Paths.get(reportDir);
        if (!Files.exists(dir)) {
            Files.createDirectories(dir);
            log.info("[DailyReportPdf] Created report directory: {}", dir);
        }
    }
}
