"""Tests for jjm_section_officer_scheme_mapping_ingest.

Two layers:

  * pure logic — CSV parsing (including the literal 'NULL' this export writes
    into imis_id), the collapse of up to 166 rows onto one officer, and the role
    gate. These run anywhere.
  * write paths — scheme resolution, stale-mapping detection and every
    INSERT/UPDATE/soft-delete against a real PostgreSQL. Resolution reads an
    index built from the tenant's own rows, the stale query joins three tables
    to isolate one role, and the writes build SQL dynamically; a mock cannot
    show that any of that executes, types its columns correctly, or lands the
    right values on the right rows.

What is deliberately *not* re-tested here is the user half — matching on phone,
the field-level diff, the protected roles, the onboarding row. That is
users/test_jjm_user_master_ingest.py's job, and this module imports the same
code. What is tested is everything the scheme/SO contract adds: resolving a
scheme by its centre id rather than through a departmental node, the fan-out
that a centre id shared by several schemes produces, and the removal rule —
which is this tool's only destructive behaviour and the one thing none of its
siblings do by default.

The tenant DDL and the user/mapping seed helpers are imported from the
division/EE suite for the same reason the production module imports its engine —
one schema definition, not two that drift.

  export JJM_TEST_DSN='postgresql://postgres:testpw@localhost:55432/shared_db'
  python3 -m pytest "scripts/jjm master data ingestion/so-scheme-mapping/test_jjm_section_officer_scheme_mapping_ingest.py" -v
"""

from __future__ import annotations

import contextlib
import os
import sys

import pandas as pd
import psycopg2
import pytest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, "div-ee-mapping")
)

from jjm_division_ee_mapping_ingest import (  # noqa: E402
    CAT_EXISTING,
    CAT_NEW,
    MAPPING_STATUS_ACTIVE,
    MAPPING_STATUS_INACTIVE,
    REMOVAL_ABSENT,
    REMOVAL_REASSIGNED,
    REMOVAL_SKIPPED,
    AnalyticsWriter,
    MappingWriter,
    RolePlan,
    UserWriter,
)
from test_jjm_division_ee_mapping_ingest import (  # noqa: E402
    ACTOR_ID,
    COMMON_DDL,
    TENANT_ID,
    _create_schema,
    _pii,
    seed_mapping,
    seed_user,
)

from jjm_section_officer_scheme_mapping_ingest import (  # noqa: E402
    MATCH_CENTRE_ID,
    MATCH_PUBLIC_ID,
    SCHEME_FANOUT,
    SCHEME_MATCHED,
    SCHEME_NO_ID,
    SCHEME_NOT_FOUND,
    SKIP_NO_SCHEME,
    SO_ROLE,
    SoDb,
    SoIngestPlan,
    build_conflict_frame,
    build_plan,
    build_scheme_frame,
    claim_key,
    collapse_officers,
    execute_analytics,
    execute_tenant,
    load_csv,
    main,
    unusable_roles,
    write_analysis_workbook,
)

DSN = os.environ.get("JJM_TEST_DSN", "postgresql://postgres:testpw@localhost:55432/shared_db")
SCHEMA = "tenant_sotest"
LEGACY_SCHEMA = "tenant_sotest_prev36"

CSV_HEADER = (
    "schemes(41),,,,\n"
    "scheme_public_id,imis_id,public_id,section_officer_name,section_officer_phone\n"
)

# Only the columns this tool reads. dim_user_scheme_mapping_table carries no
# foreign key to either dimension (V16/V32 dropped them), which is exactly why
# count_missing_dim_schemes exists — so the DDL must not re-add one.
ANALYTICS_DDL = """
CREATE TABLE analytics_schema.dim_tenant_table (
    tenant_id  INTEGER      PRIMARY KEY,
    state_code VARCHAR(10)  NOT NULL,
    title      VARCHAR(255) NOT NULL,
    status     INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE analytics_schema.dim_user_table (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER      NOT NULL,
    tenant_id  INTEGER      NOT NULL REFERENCES analytics_schema.dim_tenant_table(tenant_id),
    email      VARCHAR(255),
    user_type  INTEGER,
    title      VARCHAR(255),
    uuid       UUID,
    status     INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uq_dim_user_tenant_user_id UNIQUE (tenant_id, user_id)
);

CREATE TABLE analytics_schema.dim_user_scheme_mapping_table (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID    NOT NULL UNIQUE,
    user_id    INTEGER NOT NULL,
    scheme_id  INTEGER NOT NULL,
    ai_reading NUMERIC,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    status     INTEGER NOT NULL,
    tenant_id  INTEGER
);

CREATE TABLE analytics_schema.dim_scheme_table (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id INTEGER NOT NULL,
    tenant_id INTEGER NOT NULL REFERENCES analytics_schema.dim_tenant_table(tenant_id)
);
"""


def write_csv(tmp_path, *lines: str) -> str:
    path = tmp_path / "map.csv"
    path.write_text(CSV_HEADER + "".join(line + "\n" for line in lines), encoding="utf-8")
    return str(path)


def rows_of(tmp_path, *lines: str):
    return load_csv(write_csv(tmp_path, *lines), header_row=2, encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# CSV parsing
# ─────────────────────────────────────────────────────────────────────────────

class TestLoadCsv:
    def test_reads_the_state_export_layout(self, tmp_path):
        """The export puts a title line above the header, and row numbers in the
        report have to line up with what the operator sees in the file."""
        rows, issues = rows_of(
            tmp_path,
            "SCH-001001,8156128,USR-015758,Ashif Ahmed,7002921268",
            "SCH-004187,8196797,USR-015758,Ashif Ahmed,7002921268",
        )

        assert [r.row_no for r in rows] == [3, 4]
        assert rows[0].scheme_public_id == "SCH-001001"
        assert rows[0].code_key == "sch-001001"
        assert rows[0].imis_id == "8156128"
        assert rows[0].imis_key == "8156128"
        assert rows[0].claim_key == "sch-001001/8156128"
        assert rows[0].user_public_id == "USR-015758"
        assert rows[0].phone == "917002921268"
        assert issues == []

    def test_every_row_is_a_section_officer_without_a_role_column(self, tmp_path):
        """The file has no role column: the role is what the file is. It must be
        applied silently rather than reported once for each of 31,684 rows."""
        rows, issues = rows_of(tmp_path, "SCH-1,100,USR-1,Some Person,9000000001")

        assert rows[0].role == SO_ROLE
        assert rows[0].role_raw == ""
        assert issues == []

    def test_a_literal_null_imis_id_still_leaves_the_public_id_to_resolve_by(self, tmp_path):
        """131 rows of this file say 'NULL' where the centre id belongs and two
        are simply blank. Both mean the same thing — and neither costs the row
        its scheme any more, because scheme_public_id is tried first."""
        rows, issues = rows_of(
            tmp_path,
            "SCH-011098,NULL,USR-041763,Pallabi Das,7896188354",
            "SCH-011112,,USR-041763,Pallabi Das,7896188354",
        )

        assert rows[0].imis_key == rows[1].imis_key == ""
        assert rows[0].code_key == "sch-011098"
        assert all(r.scheme_issues == [] for r in rows)
        assert issues == []

    def test_a_row_naming_neither_id_loses_its_scheme_but_not_its_officer(self, tmp_path):
        """Only a row with nothing to resolve by is unusable, and even then the
        officer is perfectly readable on their other 40 rows."""
        rows, issues = rows_of(
            tmp_path,
            ",NULL,USR-041763,Pallabi Das,7896188354",
            "SCH-011113,8156128,USR-041763,Pallabi Das,7896188354",
        )

        assert rows[0].scheme_issues and rows[0].blocking_issues == []
        assert rows[1].scheme_issues == []
        assert {i["issue_kind"] for i in issues} == {"scheme"}

    def test_leading_zeros_do_not_make_a_different_centre_id(self, tmp_path):
        rows, _ = rows_of(
            tmp_path,
            "SCH-1,0008156128,USR-1,A,9000000001",
            "SCH-2,8156128,USR-2,B,9000000002",
        )

        assert rows[0].imis_key == rows[1].imis_key == "8156128"

    def test_flags_unusable_rows_without_echoing_the_number(self, tmp_path):
        """An invalid phone is reported, but the number itself is PII and must
        not be written into the issue text."""
        rows, issues = rows_of(
            tmp_path,
            "SCH-1,100,USR-1,Bad Phone,1234567890",
            "SCH-2,200,USR-2,,9000000002",
            "SCH-3,300,,No Public Id,9000000003",
        )

        assert rows[0].blocking_issues == [
            "row:section_officer_phone is not a valid Indian mobile number"
        ]
        assert rows[1].blocking_issues == ["row:blank section_officer_name"]
        # A missing public_id alone is reported, never blocking.
        assert rows[2].blocking_issues == []
        assert not any("1234567890" in i["issue"] for i in issues)

    def test_issue_records_use_the_csv_vocabulary(self, tmp_path):
        _, issues = rows_of(tmp_path, ",NULL,,No Ids,9000000004")

        assert {i["issue_kind"] for i in issues} == {"scheme", "state_user_id"}
        assert "scheme_public_id" in issues[0]
        assert "imis_id" in issues[0]

    def test_the_real_export_parses(self):
        """The file this tool exists for, as shipped: 31,684 rows over 691
        officers. 133 rows carry no usable centre id, and every one of those
        still names a scheme_public_id to be resolved by."""
        csv_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "section-officer-scheme-mapping.csv"
        )
        if not os.path.exists(csv_path):
            pytest.skip("the state export is not checked out here")

        rows, _ = load_csv(csv_path, header_row=2, encoding="utf-8-sig")
        officers, _ = collapse_officers(rows)

        assert len(rows) == 31684
        assert all(r.role == SO_ROLE for r in rows)
        assert len([r for r in rows if r.blocking_issues]) == 0
        assert len([r for r in rows if not r.imis_key]) == 133
        assert all(r.code_key for r in rows)
        assert len([r for r in rows if r.scheme_issues]) == 0
        assert len(officers) == 691


# ─────────────────────────────────────────────────────────────────────────────
# Collapsing an officer spread over many rows
# ─────────────────────────────────────────────────────────────────────────────

class TestCollapseOfficers:
    def test_one_officer_over_many_rows_becomes_one_user_row(self, tmp_path):
        rows, _ = rows_of(
            tmp_path,
            "SCH-1,100,USR-1,Same Person,9000000001",
            "SCH-2,200,USR-1,Same Person,9000000001",
            "SCH-3,300,USR-2,Other Person,9000000002",
        )

        user_rows, grouped = collapse_officers(rows)

        assert len(user_rows) == 2
        assert user_rows[0].phone == "919000000001"
        assert [r.row_no for r in grouped["919000000001"]] == [3, 4]

    def test_name_and_public_id_are_taken_across_the_group(self, tmp_path):
        """Not off whichever row came first: an officer with 166 rows may have a
        gap on the one that happens to sort first, and that must not onboard
        them nameless — or block them as an unusable row."""
        rows, _ = rows_of(
            tmp_path,
            "SCH-1,100,,,9000000001",
            "SCH-2,200,USR-7,Pallabi Das,9000000001",
        )

        user_rows, _ = collapse_officers(rows)

        assert len(user_rows) == 1
        assert user_rows[0].name == "Pallabi Das"
        assert user_rows[0].public_id == "USR-7"
        assert user_rows[0].blocking_issues == []

    def test_an_officer_with_no_name_anywhere_is_still_unusable(self, tmp_path):
        rows, _ = rows_of(tmp_path, "SCH-1,100,USR-1,,9000000001")

        user_rows, _ = collapse_officers(rows)

        assert user_rows[0].blocking_issues == ["row:blank section_officer_name"]

    def test_rows_with_no_usable_number_stay_separate(self, tmp_path):
        """Two people we cannot identify are not the same person."""
        rows, _ = rows_of(
            tmp_path,
            "SCH-1,100,USR-1,A,111",
            "SCH-2,200,USR-2,B,222",
        )

        user_rows, _ = collapse_officers(rows)

        assert len(user_rows) == 2


# ─────────────────────────────────────────────────────────────────────────────
# The role gate
# ─────────────────────────────────────────────────────────────────────────────

def _plan_with_role(action: str, existing_id=None) -> SoIngestPlan:
    return SoIngestPlan(
        engineers=[], divisions={}, user_types={}, csv_issues=[],
        role_plans=[RolePlan(
            role=SO_ROLE, csv_slugs=[], csv_rows=7,
            existing_id=existing_id, action=action,
        )],
    )


class TestUnusableRoles:
    def test_the_expected_case_is_silent(self):
        assert unusable_roles(_plan_with_role("existing", existing_id=4)) == []

    def test_a_missing_role_blocks_rather_than_being_created(self):
        """Minting a second SECTION_OFFICER would split the role in two, strand
        whichever officers landed on the wrong id, and make the stale-mapping
        query blind to every mapping held under the other one."""
        problems = unusable_roles(_plan_with_role("create"))

        assert len(problems) == 1
        assert "not in common_schema.user_type_master_table" in problems[0]
        assert "7 officer(s)" in problems[0]

    def test_a_soft_deleted_role_blocks(self):
        problems = unusable_roles(_plan_with_role("blocked_soft_deleted", existing_id=9))

        assert len(problems) == 1
        assert "soft-deleted" in problems[0]


# ─────────────────────────────────────────────────────────────────────────────
# The CLI guard
# ─────────────────────────────────────────────────────────────────────────────

# A DSN nothing can be listening on, so a run that gets *past* the guard dies on
# connect instead of writing to whatever tenant_as the runner happens to have.
UNREACHABLE_DSN = "postgresql://postgres:x@127.0.0.1:1/none"


def _cli(tmp_path, *extra: str) -> list[str]:
    return [
        "--csv", write_csv(tmp_path, "SCH-1,100,USR-1,A,9000000001"),
        "--actor-id", "1", "--tenant-dsn", UNREACHABLE_DSN, "--skip-analytics",
        "--out", str(tmp_path / "out.xlsx"), *extra,
    ]


def _run_cli(tmp_path, *extra: str) -> None:
    """Call main and swallow whatever it hits once the guard has let it through."""
    with contextlib.suppress(Exception, SystemExit):
        main(_cli(tmp_path, *extra))


class TestCli:
    def test_a_truncated_run_may_not_execute_a_removal(self, tmp_path, caplog):
        """One row per scheme means a cut file is a cut statement of who covers
        what — every mapping past the cut would read as taken away."""
        code = main(_cli(tmp_path, "--limit", "1", "--execute"))

        assert code == 2
        assert "--limit cannot be combined with --execute" in caplog.text

    def test_a_truncated_rehearsal_is_fine(self, tmp_path, caplog):
        _run_cli(tmp_path, "--limit", "1")

        assert "--limit cannot be combined" not in caplog.text

    def test_a_truncated_run_may_execute_when_it_removes_nothing(self, tmp_path, caplog):
        _run_cli(tmp_path, "--limit", "1", "--execute", "--additive")

        assert "--limit cannot be combined" not in caplog.text

    def test_a_zero_limit_is_refused_rather_than_ignored(self, tmp_path, caplog):
        """A falsy limit used to slip past both the guard and the slice, so
        --limit 0 --execute quietly ran the whole file."""
        code = main(_cli(tmp_path, "--limit", "0", "--execute"))

        assert code == 2
        assert "--limit must be a positive number of rows" in caplog.text


# ─────────────────────────────────────────────────────────────────────────────
# Database-backed fixtures
# ─────────────────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def conn():
    try:
        connection = psycopg2.connect(DSN)
    except psycopg2.OperationalError as exc:
        pytest.skip(f"no PostgreSQL at {DSN}: {exc}")
    connection.autocommit = False
    yield connection
    connection.close()


@pytest.fixture
def conn_ready(conn):
    """A throwaway schema inside a transaction that is never committed.

    Nothing here commits, so the rollback at teardown removes the schemas, the
    users and any role row a test created — PostgreSQL rolls DDL back like any
    other statement. That is deliberate: pointing JJM_TEST_DSN at a database
    that matters must not be able to destroy anything in it.
    """
    conn.rollback()  # clear a transaction a previous failure may have aborted
    with conn.cursor() as cur:
        cur.execute("CREATE SCHEMA IF NOT EXISTS common_schema")
        cur.execute(COMMON_DDL)
        # Additive: a real database already holds these, and their ids are read
        # back rather than assumed.
        cur.execute(
            "INSERT INTO common_schema.user_type_master_table (c_name) "
            "VALUES ('SECTION_OFFICER'), ('PUMP_OPERATOR'), ('SUB_DIVISIONAL_OFFICER'), "
            "('STATE_ADMIN') ON CONFLICT (c_name) DO NOTHING"
        )
        _create_schema(cur, SCHEMA, with_columns=True)
        _create_schema(cur, LEGACY_SCHEMA, with_columns=False)
        # V39, which the division/EE DDL predates: the public scheme code this
        # tool resolves by, and the partial UNIQUE index that makes one code at
        # most one live scheme. LEGACY_SCHEMA deliberately goes without it.
        cur.execute(
            f"ALTER TABLE {SCHEMA}.scheme_master_table "
            f"ADD COLUMN state_scheme_code VARCHAR(255)"
        )
        cur.execute(
            f"CREATE UNIQUE INDEX uq_{SCHEMA}_scheme_state_scheme_code "
            f"ON {SCHEMA}.scheme_master_table(state_scheme_code) "
            f"WHERE state_scheme_code IS NOT NULL AND deleted_at IS NULL"
        )
        cur.execute("DROP SCHEMA IF EXISTS analytics_schema CASCADE")
        cur.execute("CREATE SCHEMA analytics_schema")
        cur.execute(ANALYTICS_DDL)
        cur.execute(
            "INSERT INTO analytics_schema.dim_tenant_table "
            "(tenant_id, state_code, title, status) VALUES (%s, 'AS', 'Assam', 1)",
            (TENANT_ID,),
        )
    yield conn
    conn.rollback()


@pytest.fixture
def db(conn_ready):
    return SoDb(conn_ready, SCHEMA, _pii(), with_state_user_id=True)


@pytest.fixture
def legacy_db(conn_ready):
    """The same tool against a tenant where neither V36 nor V39 has been applied."""
    return SoDb(conn_ready, LEGACY_SCHEMA, _pii(), with_state_user_id=False)


@pytest.fixture
def roles(db) -> dict[str, int]:
    return {name: row.id for name, row in db.load_user_types().items()}


@pytest.fixture
def writers(db):
    return UserWriter(db, TENANT_ID, ACTOR_ID), MappingWriter(db, ACTOR_ID)


def seed_scheme(db: SoDb, centre_id: str, state_id: str = "", name: str = "",
                deleted: bool = False, is_active: bool = True,
                public_code: str = "") -> int:
    """A scheme identified the way the tenant identifies one: a centre id and a
    state id, unique as a pair rather than singly, plus the state's public code
    where V39 has landed and the backfill has reached this scheme."""
    code_column = ", state_scheme_code" if public_code else ""
    code_value = ", %s" if public_code else ""
    with db.conn.cursor() as cur:
        cur.execute(
            f"INSERT INTO {db.schema}.scheme_master_table "
            f"(uuid, state_scheme_id, centre_scheme_id, scheme_name, is_active, "
            f"deleted_at{code_column}) "
            f"VALUES (gen_random_uuid()::text, %s, %s, %s, %s, "
            f"{'NOW()' if deleted else 'NULL'}{code_value}) RETURNING id",
            (state_id or centre_id, centre_id, name or f"Scheme {centre_id}", is_active,
             *((public_code,) if public_code else ())),
        )
        return cur.fetchone()[0]


def seed_dim_scheme(db: SoDb, scheme_id: int) -> None:
    with db.conn.cursor() as cur:
        cur.execute(
            "INSERT INTO analytics_schema.dim_scheme_table (scheme_id, tenant_id) "
            "VALUES (%s, %s)", (scheme_id, TENANT_ID),
        )


def plan_for(db, tmp_path, *lines: str, **kwargs) -> SoIngestPlan:
    rows, issues = rows_of(tmp_path, *lines)
    return build_plan(rows, issues, db, **kwargs)


def officer(plan: SoIngestPlan, index: int = 0):
    return plan.officers[index]


def live_mappings(db: SoDb, user_id: int) -> set[int]:
    with db.conn.cursor() as cur:
        cur.execute(
            f"SELECT scheme_id FROM {db.schema}.user_scheme_mapping_table "
            f"WHERE user_id = %s AND deleted_at IS NULL", (user_id,)
        )
        return {scheme_id for (scheme_id,) in cur}


# ─────────────────────────────────────────────────────────────────────────────
# Scheme resolution
# ─────────────────────────────────────────────────────────────────────────────

class TestSchemeResolution:
    def test_resolves_a_scheme_by_its_centre_id(self, db, tmp_path):
        scheme = seed_scheme(db, "8156128", "19394")

        plan = plan_for(db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-001001", "8156128")]
        assert resolved.category == SCHEME_MATCHED
        assert resolved.matched_on == MATCH_CENTRE_ID
        assert resolved.scheme_ids == {scheme}
        assert resolved.public_ids == ["SCH-001001"]

    def test_the_public_id_resolves_the_scheme_before_the_centre_id_is_tried(
        self, db, tmp_path
    ):
        """state_scheme_code is unique per live scheme, so it answers exactly;
        the centre id it shares with another scheme never gets a say."""
        wanted = seed_scheme(db, "8156128", "19394", public_code="SCH-001001")
        seed_scheme(db, "8156128", "19395", public_code="SCH-001002")

        plan = plan_for(db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-001001", "8156128")]
        assert resolved.category == SCHEME_MATCHED
        assert resolved.matched_on == MATCH_PUBLIC_ID
        assert resolved.scheme_ids == {wanted}
        assert resolved.fallback_reason == ""
        assert officer(plan).target_scheme_ids == {wanted}

    def test_the_public_id_splits_a_centre_id_two_officers_share(self, db, tmp_path):
        """The 383 contested fan-outs are exactly this shape: one centre id,
        two officers, one scheme each. The public code is what tells them
        apart, so neither officer is granted the other's scheme."""
        first_scheme = seed_scheme(db, "8156128", "19394", public_code="SCH-001001")
        second_scheme = seed_scheme(db, "8156128", "19395", public_code="SCH-001002")

        plan = plan_for(
            db, tmp_path,
            "SCH-001001,8156128,USR-1,First Officer,9000000001",
            "SCH-001002,8156128,USR-2,Second Officer,9000000002",
        )

        first, second = plan.officers
        assert first.target_scheme_ids == {first_scheme}
        assert second.target_scheme_ids == {second_scheme}
        assert all(len(s.claimants) == 1 for s in plan.named_schemes)

    def test_case_and_whitespace_do_not_hide_a_public_id_match(self, db, tmp_path):
        scheme = seed_scheme(db, "8156128", "19394", public_code=" sch-001001 ")

        plan = plan_for(db, tmp_path, "SCH-001001,9999999,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-001001", "9999999")]
        assert resolved.matched_on == MATCH_PUBLIC_ID
        assert resolved.scheme_ids == {scheme}

    def test_a_public_id_we_do_not_hold_falls_back_to_the_centre_id(self, db, tmp_path):
        """Until state_scheme_code is backfilled this is every row, so the
        fall-back has to map exactly what it mapped before — and say it did."""
        scheme = seed_scheme(db, "8156128", "19394")

        plan = plan_for(db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-001001", "8156128")]
        assert resolved.category == SCHEME_MATCHED
        assert resolved.matched_on == MATCH_CENTRE_ID
        assert resolved.scheme_ids == {scheme}
        assert "no live scheme carries state_scheme_code 'SCH-001001'" in resolved.reason

    def test_a_public_id_resolves_a_row_whose_imis_id_is_null(self, db, tmp_path):
        """131 rows of the export say 'NULL' where the centre id belongs. With
        the public code held, those rows are no longer unmappable."""
        scheme = seed_scheme(db, "8156128", "19394", public_code="SCH-011098")

        plan = plan_for(db, tmp_path, "SCH-011098,NULL,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-011098", "")]
        assert resolved.matched_on == MATCH_PUBLIC_ID
        assert resolved.scheme_ids == {scheme}
        assert SCHEME_NO_ID not in plan.schemes

    def test_a_row_with_only_an_unknown_public_id_resolves_to_nothing(self, db, tmp_path):
        seed_scheme(db, "8156128", "19394")

        plan = plan_for(db, tmp_path, "SCH-011098,NULL,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-011098", "")]
        assert resolved.category == SCHEME_NOT_FOUND
        assert "no imis_id to fall back to" in resolved.reason
        assert officer(plan).skip_reason == SKIP_NO_SCHEME

    def test_a_tenant_without_v39_resolves_by_the_centre_id_alone(
        self, legacy_db, tmp_path
    ):
        """The column is checked for, not assumed: on a pre-V39 tenant the tool
        behaves exactly as it did before it existed, and says why."""
        scheme = seed_scheme(legacy_db, "8156128", "19394")

        plan = plan_for(legacy_db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-001001", "8156128")]
        assert resolved.matched_on == MATCH_CENTRE_ID
        assert resolved.scheme_ids == {scheme}
        assert "no state_scheme_code column (V39)" in resolved.reason

    def test_a_soft_deleted_scheme_does_not_answer_for_its_public_id(self, db, tmp_path):
        """The partial UNIQUE index skips deleted rows, so a retired scheme can
        still hold the code — it must not be resolved by it."""
        seed_scheme(db, "8156128", "19394", public_code="SCH-001001", deleted=True)
        live = seed_scheme(db, "8156128", "19395")

        plan = plan_for(db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-001001", "8156128")]
        assert resolved.matched_on == MATCH_CENTRE_ID
        assert resolved.scheme_ids == {live}

    def test_a_centre_id_shared_by_several_schemes_maps_none_of_them(self, db, tmp_path):
        """scheme_master_table is unique on the (state, centre) pair, so one
        centre id legitimately covers several schemes — and the state's file says
        so too, giving 4,003 of its imis_ids more than one scheme_public_id.
        Which of them the row means is not guessed at: the claim is refused."""
        seed_scheme(db, "8156128", "19394")
        seed_scheme(db, "8156128", "19395")

        plan = plan_for(
            db, tmp_path,
            "SCH-001001,8156128,USR-1,A,9000000001",
            "SCH-001002,8156128,USR-1,A,9000000001",
        )

        claims = [plan.schemes[claim_key(code, "8156128")]
                  for code in ("SCH-001001", "SCH-001002")]
        assert all(c.category == SCHEME_FANOUT for c in claims)
        assert all(c.scheme_ids == set() for c in claims)
        assert all("--map-ambiguous-schemes" in c.reason for c in claims)
        assert officer(plan).target_scheme_ids == set()
        assert officer(plan).skip_reason == SKIP_NO_SCHEME

    def test_map_ambiguous_schemes_opts_back_into_the_fan_out(self, db, tmp_path):
        first = seed_scheme(db, "8156128", "19394")
        second = seed_scheme(db, "8156128", "19395")

        plan = plan_for(
            db, tmp_path,
            "SCH-001001,8156128,USR-1,A,9000000001",
            "SCH-001002,8156128,USR-1,A,9000000001",
            map_ambiguous_schemes=True,
        )

        claims = [plan.schemes[claim_key(code, "8156128")]
                  for code in ("SCH-001001", "SCH-001002")]
        assert all(c.category == SCHEME_FANOUT for c in claims)
        assert all(c.scheme_ids == {first, second} for c in claims)
        assert officer(plan).target_scheme_ids == {first, second}

    def test_an_ambiguous_claim_is_not_dressed_up_as_a_match_on_the_sheets(
        self, db, tmp_path
    ):
        """'MATCHED_SEVERAL' is what happened to the id, not what happened to the
        officer — the conflicts sheet has to say the claim was dropped."""
        seed_scheme(db, "8156128", "19394")
        seed_scheme(db, "8156128", "19395")

        plan = plan_for(db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        conflicts = build_conflict_frame(plan, include_pii=False)
        assert "SCHEME_AMBIGUOUS_NOT_MAPPED" in set(conflicts["kind"])

    def test_the_public_ids_we_do_not_hold_are_reported_as_one_record(self, db, tmp_path):
        """Every claim falls back until state_scheme_code is backfilled, so the
        conflicts sheet gets the size of the gap and what it cost — not 31,000
        identical rows that would bury everything else on it."""
        seed_scheme(db, "8156128", "19394")
        seed_scheme(db, "8156128", "19395")
        seed_scheme(db, "100", "19396")

        plan = plan_for(
            db, tmp_path,
            "SCH-001001,8156128,USR-1,A,9000000001",
            "SCH-001002,100,USR-1,A,9000000001",
        )

        conflicts = build_conflict_frame(plan, include_pii=False)
        gap = conflicts[conflicts["kind"] == "SCHEME_PUBLIC_ID_UNKNOWN_HERE"]
        assert len(gap) == 1
        assert "2 claim(s) name a scheme_public_id no live scheme carries" in \
            gap.iloc[0]["detail"]
        assert "1 of those match several schemes each" in gap.iloc[0]["detail"]
        assert "are mapped to none of them" in gap.iloc[0]["detail"]

    def test_a_pre_v39_tenant_says_so_on_the_conflicts_sheet(self, legacy_db, tmp_path):
        seed_scheme(legacy_db, "8156128", "19394")

        plan = plan_for(legacy_db, tmp_path, "SCH-001001,8156128,USR-1,A,9000000001")

        conflicts = build_conflict_frame(plan, include_pii=False)
        gap = conflicts[conflicts["kind"] == "SCHEME_PUBLIC_ID_UNKNOWN_HERE"]
        assert len(gap) == 1
        assert "no state_scheme_code column (V39)" in gap.iloc[0]["detail"]

    def test_an_officer_whose_every_claim_is_ambiguous_is_not_written(self, db, tmp_path):
        seed_scheme(db, "8156128", "19394")
        seed_scheme(db, "8156128", "19395")

        plan = plan_for(db, tmp_path, "SCH-1,8156128,USR-1,A,9000000001")

        assert not officer(plan).will_write

    def test_an_unknown_centre_id_is_reported_not_guessed(self, db, tmp_path):
        seed_scheme(db, "8156128", "19394")

        plan = plan_for(db, tmp_path, "SCH-1,9999999,USR-1,A,9000000001")

        resolved = plan.schemes[claim_key("SCH-1", "9999999")]
        assert resolved.category == SCHEME_NOT_FOUND
        assert not resolved.resolved
        assert officer(plan).skip_reason == SKIP_NO_SCHEME

    def test_a_deleted_scheme_is_not_a_candidate(self, db, tmp_path):
        seed_scheme(db, "8156128", "19394", deleted=True)

        plan = plan_for(db, tmp_path, "SCH-1,8156128,USR-1,A,9000000001")

        assert plan.schemes[claim_key("SCH-1", "8156128")].category == SCHEME_NOT_FOUND

    def test_an_inactive_scheme_is_still_the_officers_to_cover(self, db, tmp_path):
        """is_active tracks recent flow readings, not responsibility."""
        scheme = seed_scheme(db, "8156128", "19394", is_active=False)

        plan = plan_for(db, tmp_path, "SCH-1,8156128,USR-1,A,9000000001")

        assert plan.schemes[claim_key("SCH-1", "8156128")].scheme_ids == {scheme}

    def test_rows_with_neither_id_collect_into_one_reported_plan(self, db, tmp_path):
        scheme = seed_scheme(db, "100")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,A,9000000001",
            ",NULL,USR-1,A,9000000001",
            ",,USR-1,A,9000000001",
        )

        no_id = plan.schemes[SCHEME_NO_ID]
        assert no_id.csv_rows == [4, 5]
        assert not no_id.resolved
        # The officer is still written, on the scheme that did resolve.
        assert officer(plan).target_scheme_ids == {scheme}
        assert plan.named_schemes == [plan.schemes[claim_key("SCH-1", "100")]]

    def test_the_scheme_sheet_names_which_id_answered(self, db, tmp_path):
        seed_scheme(db, "100", "19394", public_code="SCH-1")
        seed_scheme(db, "200", "19395")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,A,9000000001",
            "SCH-2,200,USR-1,A,9000000001",
        )

        frame = build_scheme_frame(plan, full=True)
        matched_on = dict(zip(frame["scheme_public_ids"], frame["matched_on"]))
        assert matched_on["SCH-1"] == MATCH_PUBLIC_ID
        assert matched_on["SCH-2"] == MATCH_CENTRE_ID


# ─────────────────────────────────────────────────────────────────────────────
# Mapping
# ─────────────────────────────────────────────────────────────────────────────

class TestMapping:
    def test_an_officer_gets_the_union_of_their_rows(self, db, tmp_path, writers):
        first = seed_scheme(db, "100")
        second = seed_scheme(db, "200")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,Ashif Ahmed,9000000001",
            "SCH-2,200,USR-1,Ashif Ahmed,9000000001",
        )
        assert len(plan.officers) == 1
        assert officer(plan).to_insert == {first, second}

        stats = execute_tenant(plan, *writers)

        assert stats["scheme_mappings_inserted"] == 2
        assert live_mappings(db, officer(plan).decision.existing_id) == {first, second}

    def test_a_mapping_already_held_is_not_inserted_again(self, db, tmp_path, roles, writers):
        held = seed_scheme(db, "100")
        wanted = seed_scheme(db, "200")
        user = seed_user(db, "A", "919000000001", roles[SO_ROLE])
        seed_mapping(db, user, held)

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,A,9000000001",
            "SCH-2,200,USR-1,A,9000000001",
        )
        assert officer(plan).to_insert == {wanted}

        stats = execute_tenant(plan, *writers)

        assert stats["scheme_mappings_inserted"] == 1
        assert stats["scheme_mappings_already_correct"] == 1
        assert live_mappings(db, user) == {held, wanted}

    def test_two_officers_on_one_centre_id_are_both_mapped(self, db, tmp_path, writers):
        """user_scheme_mapping is many-to-many, so two officers covering one
        centre id is a fact the CSV is allowed to state — 383 of them do."""
        scheme = seed_scheme(db, "100")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,First Officer,9000000001",
            "SCH-1,100,USR-2,Second Officer,9000000002",
        )
        execute_tenant(plan, *writers)

        assert len(plan.officers) == 2
        assert all(live_mappings(db, p.decision.existing_id) == {scheme}
                   for p in plan.officers)


# ─────────────────────────────────────────────────────────────────────────────
# Stale mappings — this tool's only destructive behaviour
# ─────────────────────────────────────────────────────────────────────────────

class TestStaleMappings:
    """The CSV is authoritative for SECTION_OFFICER, tenant-wide.

    Every live mapping of that role which the file does not restate is retired,
    whether it belongs to an officer the file names, an officer it names but
    could not process, or one it has dropped altogether. Only another role's
    mapping is out of reach.
    """

    def test_a_scheme_handed_to_another_officer_is_taken_off_the_old_one(
        self, db, tmp_path, roles, writers
    ):
        scheme = seed_scheme(db, "100")
        previous = seed_user(db, "Previous Officer", "919000000009", roles[SO_ROLE])
        seed_mapping(db, previous, scheme)

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,New Officer,9000000001")
        assert [(r.user_id, r.scheme_id) for r in plan.reconciliation.coverage_removals] \
            == [(previous, scheme)]

        stats = execute_tenant(plan, *writers)

        assert stats["scheme_mappings_retired"] == 1
        assert live_mappings(db, previous) == set()
        assert live_mappings(db, officer(plan).decision.existing_id) == {scheme}

    def test_an_officer_in_the_csv_loses_the_schemes_it_no_longer_gives_them(
        self, db, tmp_path, roles, writers
    ):
        kept = seed_scheme(db, "100")
        moved = seed_scheme(db, "200")
        first = seed_user(db, "First", "919000000001", roles[SO_ROLE])
        seed_user(db, "Second", "919000000002", roles[SO_ROLE])
        seed_mapping(db, first, kept)
        seed_mapping(db, first, moved)

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,First,9000000001",
            "SCH-2,200,USR-2,Second,9000000002",
        )
        assert officer(plan, 0).to_remove == {moved}
        assert [r.reason for r in plan.reconciliation.coverage_removals] == [REMOVAL_REASSIGNED]

        execute_tenant(plan, *writers)

        assert live_mappings(db, first) == {kept}

    def test_an_ambiguous_claim_takes_away_what_the_officer_held_under_it(
        self, db, tmp_path, roles, writers
    ):
        """A refused claim is not a claim left alone. The officer is written on
        what the CSV states unambiguously, and the schemes behind the ambiguous
        id go the way of everything else the file no longer states."""
        stated = seed_scheme(db, "100")
        first = seed_scheme(db, "200", "A")
        second = seed_scheme(db, "200", "B")
        holder = seed_user(db, "Officer", "919000000001", roles[SO_ROLE])
        for scheme in (stated, first, second):
            seed_mapping(db, holder, scheme)

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,Officer,9000000001",
            "SCH-2,200,USR-1,Officer,9000000001",
        )
        assert officer(plan).target_scheme_ids == {stated}
        assert officer(plan).to_remove == {first, second}

        execute_tenant(plan, *writers)

        assert live_mappings(db, holder) == {stated}

    def test_map_ambiguous_schemes_keeps_those_mappings_instead(
        self, db, tmp_path, roles, writers
    ):
        stated = seed_scheme(db, "100")
        first = seed_scheme(db, "200", "A")
        second = seed_scheme(db, "200", "B")
        holder = seed_user(db, "Officer", "919000000001", roles[SO_ROLE])
        for scheme in (stated, first, second):
            seed_mapping(db, holder, scheme)

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,Officer,9000000001",
            "SCH-2,200,USR-1,Officer,9000000001",
            map_ambiguous_schemes=True,
        )
        assert plan.reconciliation.coverage_removals == []

        execute_tenant(plan, *writers)

        assert live_mappings(db, holder) == {stated, first, second}

    def test_an_officer_left_with_no_unambiguous_scheme_is_stripped_entirely(
        self, db, tmp_path, roles, writers
    ):
        """Nothing the run can vouch for is left, so nothing survives — the same
        rule that governs an officer whose ids resolved to nothing at all."""
        first = seed_scheme(db, "200", "A")
        second = seed_scheme(db, "200", "B")
        holder = seed_user(db, "Officer", "919000000001", roles[SO_ROLE])
        seed_mapping(db, holder, first)
        seed_mapping(db, holder, second)

        plan = plan_for(db, tmp_path, "SCH-1,200,USR-1,Officer,9000000001")
        assert not officer(plan).will_write
        assert {r.reason for r in plan.reconciliation.coverage_removals} == {REMOVAL_SKIPPED}

        execute_tenant(plan, *writers)

        assert live_mappings(db, holder) == set()

    def test_additive_keeps_what_an_ambiguous_claim_would_have_taken(
        self, db, tmp_path, roles, writers
    ):
        first = seed_scheme(db, "200", "A")
        seed_scheme(db, "200", "B")          # makes the claim ambiguous
        holder = seed_user(db, "Officer", "919000000001", roles[SO_ROLE])
        seed_mapping(db, holder, first)

        plan = plan_for(db, tmp_path, "SCH-1,200,USR-1,Officer,9000000001", replace=False)

        execute_tenant(plan, *writers)

        assert live_mappings(db, holder) == {first}

    def test_another_roles_mapping_on_the_same_scheme_is_never_touched(
        self, db, tmp_path, roles, writers
    ):
        """user_scheme_mapping_table is shared with pump operators, jal sahayaks,
        EEs and SDOs. This file speaks only for section officers."""
        scheme = seed_scheme(db, "100")
        operator = seed_user(db, "Jal Mitra", "919000000008", roles["PUMP_OPERATOR"])
        sdo = seed_user(db, "An SDO", "919000000007", roles["SUB_DIVISIONAL_OFFICER"])
        seed_mapping(db, operator, scheme)
        seed_mapping(db, sdo, scheme)

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,New Officer,9000000001")
        assert plan.reconciliation.removals == []

        execute_tenant(plan, *writers)

        assert live_mappings(db, operator) == {scheme}
        assert live_mappings(db, sdo) == {scheme}

    def test_a_legacy_officer_loses_even_a_scheme_the_csv_never_names(
        self, db, tmp_path, roles, writers
    ):
        """Requirement 5: absence from the dataset is a statement about the
        person, not about the schemes they happen to hold."""
        named = seed_scheme(db, "100")
        elsewhere = seed_scheme(db, "999")
        holder = seed_user(db, "Legacy Officer", "919000000009", roles[SO_ROLE])
        seed_mapping(db, holder, elsewhere)

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,New Officer,9000000001")
        assert [r.reason for r in plan.reconciliation.coverage_removals] == [REMOVAL_ABSENT]

        execute_tenant(plan, *writers)

        assert live_mappings(db, holder) == set()
        assert live_mappings(db, officer(plan).decision.existing_id) == {named}

    def test_an_officer_the_csv_names_but_could_not_process_is_stripped_and_labelled(
        self, db, tmp_path, roles, writers
    ):
        """Named but unresolvable is still 'not in the latest snapshot'. It is
        reported under its own reason so the operator can tell the two apart."""
        scheme = seed_scheme(db, "100")
        holder = seed_user(db, "Known Officer", "919000000001", roles[SO_ROLE])
        seed_mapping(db, holder, scheme)

        # Same phone, but the centre id on their only row does not resolve, so
        # the officer is skipped rather than written.
        plan = plan_for(db, tmp_path, "SCH-1,777,USR-1,Known Officer,9000000001")
        assert not officer(plan).will_write
        assert [r.reason for r in plan.reconciliation.coverage_removals] == [REMOVAL_SKIPPED]
        assert "no scheme" in plan.reconciliation.coverage_removals[0].detail

        execute_tenant(plan, *writers)

        assert live_mappings(db, holder) == set()

    def test_additive_removes_nothing(self, db, tmp_path, roles, writers):
        scheme = seed_scheme(db, "100")
        previous = seed_user(db, "Previous", "919000000009", roles[SO_ROLE])
        seed_mapping(db, previous, scheme)

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,New Officer,9000000001",
                        replace=False)
        assert plan.reconciliation.removals == []
        assert plan.deactivate_row_ids == []

        stats = execute_tenant(plan, *writers)

        assert stats["scheme_mappings_retired"] == 0
        assert live_mappings(db, previous) == {scheme}

    def test_the_removal_is_a_soft_delete_with_an_audit_trail(
        self, db, tmp_path, roles, writers
    ):
        """Mirrors UserUploadRepository — the row stays, deleted_at/deleted_by
        record who dropped it and when — and additionally drops status to 0,
        which every service read path already demands alongside deleted_at."""
        scheme = seed_scheme(db, "100")
        previous = seed_user(db, "Previous", "919000000009", roles[SO_ROLE])
        seed_mapping(db, previous, scheme)

        execute_tenant(plan_for(db, tmp_path, "SCH-1,100,USR-1,New,9000000001"), *writers)

        with db.conn.cursor() as cur:
            cur.execute(
                f"SELECT deleted_at IS NOT NULL, deleted_by, status "
                f"FROM {SCHEMA}.user_scheme_mapping_table "
                f"WHERE user_id = %s AND scheme_id = %s", (previous, scheme)
            )
            assert cur.fetchone() == (True, ACTOR_ID, MAPPING_STATUS_INACTIVE)

    def test_a_rerun_of_the_same_csv_changes_nothing(self, db, tmp_path, roles, writers):
        """Idempotence is what makes this safe to run again after a fix."""
        scheme = seed_scheme(db, "100")
        line = "SCH-1,100,USR-1,Ashif Ahmed,9000000001"

        execute_tenant(plan_for(db, tmp_path, line), *writers)
        second = plan_for(db, tmp_path, line)

        assert second.insert_pairs == []
        assert second.deactivate_row_ids == []
        assert second.resurrect_row_ids == []
        stats = execute_tenant(second, *writers)
        assert stats["scheme_mappings_inserted"] == 0
        assert stats["scheme_mappings_retired"] == 0
        assert stats["scheme_mappings_revived"] == 0

    def test_a_scheme_taken_away_and_given_back_reuses_the_same_row(
        self, db, tmp_path, roles, writers
    ):
        """Requirement 2 and 4 together: no second row is ever created."""
        scheme = seed_scheme(db, "100")
        line = "SCH-1,100,USR-1,Ashif Ahmed,9000000001"
        execute_tenant(plan_for(db, tmp_path, line), *writers)
        user = officer(plan_for(db, tmp_path, line)).decision.existing_id

        # A run that does not mention them at all retires the mapping ...
        execute_tenant(plan_for(db, tmp_path, "SCH-2,200,USR-2,Someone Else,9000000002"),
                       *writers)
        assert live_mappings(db, user) == set()

        # ... and putting them back revives the row rather than adding one.
        stats = execute_tenant(plan_for(db, tmp_path, line), *writers)

        assert stats["scheme_mappings_revived"] == 1
        assert stats["scheme_mappings_inserted"] == 0
        with db.conn.cursor() as cur:
            cur.execute(
                f"SELECT COUNT(*) FROM {SCHEMA}.user_scheme_mapping_table "
                f"WHERE user_id = %s AND scheme_id = %s", (user, scheme))
            assert cur.fetchone()[0] == 1


# ─────────────────────────────────────────────────────────────────────────────
# Officers
# ─────────────────────────────────────────────────────────────────────────────

class TestOfficers:
    def test_a_new_officer_is_onboarded_with_the_so_email_prefix(
        self, db, tmp_path, roles, writers
    ):
        scheme = seed_scheme(db, "100")

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-015758,Ashif Ahmed,9000000001")
        assert officer(plan).decision.category == CAT_NEW

        stats = execute_tenant(plan, *writers)

        assert stats["users_inserted"] == 1
        assert stats["user_types_created"] == 0    # the role already existed
        user_id = officer(plan).decision.existing_id
        with db.conn.cursor() as cur:
            cur.execute(
                f"SELECT email, user_type, state_user_id FROM {SCHEMA}.user_table "
                f"WHERE id = %s", (user_id,)
            )
            email, user_type, state_user_id = cur.fetchone()
        assert email.startswith("so_919000000001")
        assert user_type == roles[SO_ROLE]
        assert state_user_id == "USR-015758"
        assert live_mappings(db, user_id) == {scheme}

    def test_an_existing_pump_operator_is_promoted(self, db, tmp_path, roles, writers):
        seed_scheme(db, "100")
        user = seed_user(db, "Old Name", "919000000001", roles["PUMP_OPERATOR"])

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,New Name,9000000001")

        decision = officer(plan).decision
        assert decision.category == CAT_EXISTING
        assert decision.changes["role"] == ("PUMP_OPERATOR", SO_ROLE)
        assert decision.changes["name"] == ("Old Name", "New Name")

        execute_tenant(plan, *writers)

        with db.conn.cursor() as cur:
            cur.execute(f"SELECT user_type FROM {SCHEMA}.user_table WHERE id = %s", (user,))
            assert cur.fetchone()[0] == roles[SO_ROLE]

    def test_an_administrator_is_never_demoted(self, db, tmp_path, roles):
        seed_scheme(db, "100")
        seed_user(db, "Admin", "919000000001", roles["STATE_ADMIN"])

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,Admin,9000000001")

        decision = officer(plan).decision
        assert "role" not in decision.changes
        assert "STATE_ADMIN" in decision.withheld["role"]

    def test_no_role_updates_withholds_the_promotion(self, db, tmp_path, roles):
        seed_scheme(db, "100")
        seed_user(db, "A", "919000000001", roles["PUMP_OPERATOR"])

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,A,9000000001", update_roles=False)

        assert "role" not in officer(plan).decision.changes
        assert "--no-role-updates" in officer(plan).decision.withheld["role"]

    def test_an_officer_with_no_resolvable_scheme_is_not_created(self, db, tmp_path, writers):
        seed_scheme(db, "100")

        plan = plan_for(db, tmp_path, "SCH-1,999,USR-1,A,9000000001")
        stats = execute_tenant(plan, *writers)

        assert stats["users_inserted"] == 0
        assert stats["scheme_mappings_inserted"] == 0

    def test_create_users_without_schemes_onboards_them_anyway(self, db, tmp_path, writers):
        seed_scheme(db, "100")

        plan = plan_for(db, tmp_path, "SCH-1,999,USR-1,A,9000000001",
                        create_users_without_schemes=True)
        stats = execute_tenant(plan, *writers)

        assert stats["users_inserted"] == 1
        assert stats["scheme_mappings_inserted"] == 0

    def test_the_role_gate_passes_against_a_seeded_database(self, db, tmp_path):
        seed_scheme(db, "100")

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,A,9000000001")

        assert [p.role for p in plan.role_plans] == [SO_ROLE]
        assert unusable_roles(plan) == []


# ─────────────────────────────────────────────────────────────────────────────
# The analytics projection
# ─────────────────────────────────────────────────────────────────────────────

class TestAnalytics:
    def test_the_warehouse_ends_up_matching_the_tenant(self, db, tmp_path, roles, writers):
        scheme = seed_scheme(db, "100")
        seed_dim_scheme(db, scheme)

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,Ashif Ahmed,9000000001")
        execute_tenant(plan, *writers)
        stats = execute_analytics(plan, AnalyticsWriter(db.conn, TENANT_ID), db)

        user_id = officer(plan).decision.existing_id
        assert stats["dim_user_rows_upserted"] == 1
        assert stats["dim_user_scheme_mapping_rows"] == 1
        assert stats["mapped_schemes_missing_from_dim_scheme"] == 0
        with db.conn.cursor() as cur:
            cur.execute(
                "SELECT title, user_type FROM analytics_schema.dim_user_table "
                "WHERE tenant_id = %s AND user_id = %s", (TENANT_ID, user_id)
            )
            assert cur.fetchone() == ("Ashif Ahmed", roles[SO_ROLE])
            cur.execute(
                "SELECT scheme_id FROM analytics_schema.dim_user_scheme_mapping_table "
                "WHERE tenant_id = %s AND user_id = %s", (TENANT_ID, user_id)
            )
            assert [r[0] for r in cur] == [scheme]

    def test_a_holder_the_csv_never_names_is_projected_too(
        self, db, tmp_path, roles, writers
    ):
        """Removing their mapping in the tenant and leaving it in the warehouse
        would keep serving coverage the tenant no longer grants."""
        scheme = seed_scheme(db, "100")
        seed_dim_scheme(db, scheme)
        previous = seed_user(db, "Previous", "919000000009", roles[SO_ROLE])
        seed_mapping(db, previous, scheme)
        with db.conn.cursor() as cur:
            cur.execute(
                "INSERT INTO analytics_schema.dim_user_scheme_mapping_table "
                "(uuid, user_id, scheme_id, status, tenant_id) "
                "VALUES (gen_random_uuid(), %s, %s, 1, %s)",
                (previous, scheme, TENANT_ID),
            )

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,New Officer,9000000001")
        assert previous in plan.affected_user_ids

        execute_tenant(plan, *writers)
        execute_analytics(plan, AnalyticsWriter(db.conn, TENANT_ID), db)

        with db.conn.cursor() as cur:
            cur.execute(
                "SELECT count(*) FROM analytics_schema.dim_user_scheme_mapping_table "
                "WHERE tenant_id = %s AND user_id = %s", (TENANT_ID, previous)
            )
            assert cur.fetchone()[0] == 0

    def test_a_mapping_whose_scheme_is_missing_from_the_warehouse_is_counted(
        self, db, tmp_path, writers
    ):
        """dim_user_scheme_mapping_table carries no scheme foreign key, so such a
        row inserts happily and then joins to nothing. It is a warning about
        scheme sync, not a reason to refuse the mapping."""
        seed_scheme(db, "100")   # deliberately not in dim_scheme_table

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,A,9000000001")
        execute_tenant(plan, *writers)
        stats = execute_analytics(plan, AnalyticsWriter(db.conn, TENANT_ID), db)

        assert stats["mapped_schemes_missing_from_dim_scheme"] == 1


# ─────────────────────────────────────────────────────────────────────────────
# Before the migration lands
# ─────────────────────────────────────────────────────────────────────────────

class TestWithoutTheMigration:
    def test_the_whole_mapping_works_without_v36(self, legacy_db, tmp_path):
        """The mapping itself never needs state_user_id, so it can be ingested
        before V36 is applied."""
        scheme = seed_scheme(legacy_db, "100")

        plan = plan_for(legacy_db, tmp_path, "SCH-1,100,USR-1,A,9000000001")
        stats = execute_tenant(
            plan,
            UserWriter(legacy_db, TENANT_ID, ACTOR_ID),
            MappingWriter(legacy_db, ACTOR_ID),
        )

        assert stats["users_inserted"] == 1
        user_id = officer(plan).decision.existing_id
        assert live_mappings(legacy_db, user_id) == {scheme}

    def test_the_missing_column_is_reported_before_anything_is_read(self, legacy_db):
        legacy_db.with_state_user_id = True

        with pytest.raises(SystemExit) as exc:
            legacy_db.assert_state_user_id_column()
        assert "V36" in str(exc.value)


# ─────────────────────────────────────────────────────────────────────────────
# The analysis workbook
# ─────────────────────────────────────────────────────────────────────────────

class TestAnalysisWorkbook:
    def test_every_sheet_is_written_and_says_section_officer(self, db, tmp_path, roles):
        """The workbook is what an operator reads before authorising a
        production write, so it has to survive every outcome the plan can hold —
        a clean match, a fan-out, an unresolvable id, a skipped person and a
        removal — and describe them in the file's own vocabulary."""
        matched = seed_scheme(db, "100", public_code="SCH-1")
        seed_scheme(db, "200", "A")
        seed_scheme(db, "200", "B")            # a fanned-out centre id
        previous = seed_user(db, "Previous Officer", "919000000009", roles[SO_ROLE])
        seed_mapping(db, previous, matched)

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,New Officer,9000000001",
            "SCH-2,200,USR-2,Fanout Officer,9000000002",
            "SCH-3,999,USR-3,Lost Officer,9000000003",
            "SCH-1,100,USR-4,Bad Phone,1234567890",
            ",NULL,USR-5,No Id Officer,9000000005",
        )
        out = tmp_path / "analysis.xlsx"
        write_analysis_workbook(plan, str(out), include_pii=False, context={"mode": "TEST"})

        book = pd.read_excel(out, sheet_name=None)
        assert set(book) == {
            "run_info", "summary", "scheme_detail", "mapping_detail", "so_detail",
            "removal_detail", "duplicate_detail", "role_summary", "analytics_summary",
            "conflicts", "csv_issues",
        }

        summary = dict(zip(book["summary"]["metric"], book["summary"]["value"]))
        assert summary["distinct scheme claims named"] == 3
        assert summary["  claims resolved"] == 1
        assert summary["    by state_scheme_code (scheme_public_id)"] == 1
        assert summary["    by centre_scheme_id (imis_id)"] == 0
        assert summary["  claims whose public id we do not hold (fell back to imis_id)"] == 2
        assert summary["  claims matching several schemes"] == 1
        assert summary[
            "    of those, refused (nothing mapped, existing mappings retired)"] == 1
        assert summary["  claims not found"] == 1
        assert summary["  rows with neither scheme id"] == 1
        # lost, fanned out, bad phone, and the one whose only row carried no id
        assert summary["  officers skipped"] == 4
        assert summary["mappings to retire (coverage lost)"] == 1
        assert summary["  because the holder is not in the latest dataset"] == 1

        kinds = set(book["conflicts"]["kind"])
        assert {"SCHEME_NOT_FOUND", "SCHEME_NO_ID_AT_ALL",
                "OFFICER_SKIPPED", "LEGACY_HOLDER_STRIPPED"} <= kinds
        # A fan-out one officer owns outright is not a conflict; scheme_detail
        # carries it, and the sheet an operator has to read stays readable.
        assert "SCHEME_CONTESTED_FANOUT" not in kinds
        assert "MATCHED_SEVERAL" in set(book["scheme_detail"]["outcome"])

        removals = book["removal_detail"]
        assert list(removals["user_id"]) == [previous]
        assert list(removals["scheme_id"]) == [matched]

    def test_the_scheme_sheet_elides_the_clean_matches_by_default(self, db, tmp_path):
        """27,000 rows of 'MATCHED' bury the handful that need a human eye."""
        seed_scheme(db, "100")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,A,9000000001",
            "SCH-2,999,USR-1,A,9000000001",
        )
        short, full = tmp_path / "short.xlsx", tmp_path / "full.xlsx"
        write_analysis_workbook(plan, str(short), include_pii=False, context={})
        write_analysis_workbook(plan, str(full), include_pii=False, context={},
                                full_scheme_sheet=True)

        assert list(pd.read_excel(short, sheet_name="scheme_detail")["imis_id"]) == [999]
        assert sorted(pd.read_excel(full, sheet_name="scheme_detail")["imis_id"]) == [100, 999]

    def test_a_contested_fan_out_is_the_one_the_conflicts_sheet_singles_out(
        self, db, tmp_path
    ):
        """One centre id, two schemes, two officers, and neither public id held
        here to split them by. Refused, nobody is over-granted and there is
        nothing to report; asked for with --map-ambiguous-schemes, both officers
        get both schemes and every one of those schemes is named."""
        first = seed_scheme(db, "200", "A")
        second = seed_scheme(db, "200", "B")
        lines = (
            "SCH-1,200,USR-1,First Officer,9000000001",
            "SCH-2,200,USR-2,Second Officer,9000000002",
        )

        refused = plan_for(db, tmp_path, *lines)
        assert all(p.target_scheme_ids == set() for p in refused.officers)
        assert "SCHEME_CONTESTED_FANOUT" not in set(
            build_conflict_frame(refused, include_pii=False)["kind"])

        mapped = plan_for(db, tmp_path, *lines, map_ambiguous_schemes=True)
        conflicts = build_conflict_frame(mapped, include_pii=False)

        contested = conflicts[conflicts["kind"] == "SCHEME_CONTESTED_FANOUT"]
        assert sorted(contested["subject"]) == [
            f"scheme {scheme} (Scheme 200)" for scheme in sorted((first, second))
        ]
        assert all("First Officer" in detail and "Second Officer" in detail
                   for detail in contested["detail"])
        assert all(p.target_scheme_ids == {first, second} for p in mapped.officers)

    def test_a_scheme_two_officers_share_outright_is_reported_apart_from_a_fan_out(
        self, db, tmp_path
    ):
        """Two officers on one scheme is a fact the CSV is allowed to state, and
        must not be dressed up as an accidental over-grant."""
        scheme = seed_scheme(db, "100", public_code="SCH-1")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,First Officer,9000000001",
            "SCH-1,100,USR-2,Second Officer,9000000002",
        )
        conflicts = build_conflict_frame(plan, include_pii=False)

        shared = conflicts[conflicts["kind"] == "SCHEME_MULTIPLE_OFFICERS"]
        assert list(shared["subject"]) == [f"scheme {scheme} (Scheme 100)"]
        assert "SCHEME_CONTESTED_FANOUT" not in set(conflicts["kind"])

    def test_two_officers_on_a_single_scheme_centre_id_are_reported_more_mildly(
        self, db, tmp_path
    ):
        seed_scheme(db, "100")

        plan = plan_for(
            db, tmp_path,
            "SCH-1,100,USR-1,First Officer,9000000001",
            "SCH-1,100,USR-2,Second Officer,9000000002",
        )
        kinds = set(build_conflict_frame(plan, include_pii=False)["kind"])

        assert "SCHEME_MULTIPLE_OFFICERS" in kinds
        assert "SCHEME_CONTESTED_FANOUT" not in kinds

    def test_phone_numbers_are_masked_unless_asked_for(self, db, tmp_path):
        seed_scheme(db, "100")

        plan = plan_for(db, tmp_path, "SCH-1,100,USR-1,A,9000000001")
        masked = tmp_path / "masked.xlsx"
        write_analysis_workbook(plan, str(masked), include_pii=False, context={})

        text = pd.read_excel(masked, sheet_name="so_detail").to_string()
        assert "9000000001" not in text
