-- Fix dim_user_table identity: user_id is not unique across tenants.
-- Introduce a surrogate primary key and enforce business-key uniqueness.
--
-- Root cause addressed:
-- - V32 dropped PK on (user_id) making it non-unique.
-- - JPA still treated user_id as @Id, causing Hibernate "Duplicate row was found and ASSERT was specified"
--   when two tenants share the same user_id.

-- 1) Deduplicate by (tenant_id, user_id) keeping the most recently updated row.
WITH ranked AS (
    SELECT
        ctid,
        ROW_NUMBER() OVER (
            PARTITION BY tenant_id, user_id
            ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST
        ) AS rn
    FROM analytics_schema.dim_user_table
)
DELETE FROM analytics_schema.dim_user_table d
USING ranked r
WHERE d.ctid = r.ctid
  AND r.rn > 1;

-- 3) Add a surrogate primary key if missing.
ALTER TABLE analytics_schema.dim_user_table
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'dim_user_table_pkey'
          AND conrelid = 'analytics_schema.dim_user_table'::regclass
    ) THEN
        ALTER TABLE analytics_schema.dim_user_table
            ADD CONSTRAINT dim_user_table_pkey PRIMARY KEY (id);
    END IF;
END$$;

-- 4) Enforce uniqueness per tenant for user_id.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_dim_user_tenant_user_id'
          AND conrelid = 'analytics_schema.dim_user_table'::regclass
    ) THEN
        ALTER TABLE analytics_schema.dim_user_table
            ADD CONSTRAINT uq_dim_user_tenant_user_id
            UNIQUE (tenant_id, user_id);
    END IF;
END$$;

