"""Tests for jjm_user_offboard.

Two layers:

  * pure logic — role selection, sheet harvesting and the sparing contract.
    These run anywhere.
  * write paths — the soft deletes against a real PostgreSQL, because a delete
    that misses a row, deletes a row it should not, or leaves status alone is
    invisible to a mock and catastrophic in production.

  export JJM_TEST_DSN='postgresql://postgres:testpw@localhost:55432/shared_db'
  python3 -m pytest "scripts/jjm master data ingestion/users/test_jjm_user_offboard.py" -v
"""

from __future__ import annotations

import base64
import os
import sys

import psycopg2
import pytest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from jjm_user_offboard import (  # noqa: E402
    CAT_ABSENT,
    CAT_ACTOR,
    CAT_HAS_LOGIN,
    CAT_IN_MASTER,
    CAT_IN_PROTECT,
    CAT_NO_PHONE,
    DEACTIVATE_ACTION,
    DEFAULT_PROTECT_CSVS,
    MASTER_SOURCE,
    OFFBOARDABLE_ROLES,
    USER_STATUS_INACTIVE,
    OffboardAnalyticsWriter,
    OffboardDb,
    OffboardPlan,
    OffboardWriter,
    PiiCrypto,
    Roster,
    build_plan,
    build_role_frame,
    ceiling_breach,
    classify_users,
    collect_master,
    execute_analytics,
    execute_tenant,
    has_managed_password,
    load_csv,
    load_protect_csv,
    main,
    parse_roles,
    resolve_protect_csvs,
)

DSN = os.environ.get("JJM_TEST_DSN", "postgresql://postgres:testpw@localhost:55432/shared_db")
SCHEMA = "tenant_offboardtest"
TENANT_ID = 1
ACTOR_ID = 1

CSV_HEADER = "users(17),,,\npublic_id,name,phone,role\n"
SO_MAPPING_HEADER = (
    "schemes(41),,,,\n"
    "scheme_public_id,imis_id,public_id,section_officer_name,section_officer_phone\n"
)
# The subdivision sheet really does ship with 'pubic_id'.
SDO_MAPPING_HEADER = (
    "subdivision-sdo-mapping,,,,\n"
    "subdivision_public_id,subdivision,pubic_id,sdo_name,sdo_phone\n"
)

DDL = """
CREATE TABLE {schema}.user_table (
    id                        SERIAL       PRIMARY KEY,
    uuid                      VARCHAR(36)  NOT NULL UNIQUE,
    tenant_id                 INTEGER      NOT NULL,
    title                     TEXT,
    title_hash                TEXT,
    email                     VARCHAR(255) UNIQUE,
    user_type                 INTEGER,
    phone_number              TEXT,
    phone_number_hash         TEXT,
    state_user_id             VARCHAR(255),
    password                  TEXT,
    status                    INTEGER,
    created_at                TIMESTAMP    NOT NULL DEFAULT NOW(),
    created_by                INTEGER,
    updated_at                TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_by                INTEGER,
    deleted_at                TIMESTAMP,
    deleted_by                INTEGER
);
CREATE TABLE {schema}.user_scheme_mapping_table (
    id         SERIAL    PRIMARY KEY,
    user_id    INTEGER   NOT NULL,
    scheme_id  INTEGER   NOT NULL,
    status     INTEGER   NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by INTEGER,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_by INTEGER,
    deleted_at TIMESTAMP,
    deleted_by INTEGER
);
"""

COMMON_DDL = """
CREATE TABLE IF NOT EXISTS common_schema.user_type_master_table (
    id         SERIAL       PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL UNIQUE DEFAULT gen_random_uuid()::TEXT,
    c_name     VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    created_by INTEGER,
    updated_by INTEGER,
    deleted_at TIMESTAMP,
    deleted_by INTEGER
);
"""

# Only the columns this tool touches.
ANALYTICS_DDL = """
CREATE TABLE analytics_schema.dim_tenant_table (
    tenant_id  INTEGER      PRIMARY KEY,
    state_code VARCHAR(10)  NOT NULL,
    title      VARCHAR(255) NOT NULL,
    status     INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE analytics_schema.dim_user_table (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER      NOT NULL,
    tenant_id  INTEGER      NOT NULL REFERENCES analytics_schema.dim_tenant_table(tenant_id),
    email      VARCHAR(255),
    user_type  INTEGER,
    title      VARCHAR(255),
    uuid       UUID,
    status     INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uq_dim_user_tenant_user_id UNIQUE (tenant_id, user_id)
);

CREATE TABLE analytics_schema.dim_user_scheme_mapping_table (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID    NOT NULL UNIQUE,
    user_id    INTEGER NOT NULL,
    scheme_id  INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    status     INTEGER NOT NULL,
    tenant_id  INTEGER
);
"""


def _pii() -> PiiCrypto:
    return PiiCrypto(
        base64.b64encode(b"\x01" * 32).decode(),
        base64.b64encode(b"\x02" * 32).decode(),
    )


def write_csv(tmp_path, name: str, header: str, *lines: str) -> str:
    path = tmp_path / name
    path.write_text(header + "".join(line + "\n" for line in lines), encoding="utf-8")
    return str(path)


def master_roster(tmp_path, *lines: str) -> Roster:
    roster = Roster()
    path = write_csv(tmp_path, "users-master.csv", CSV_HEADER, *lines)
    rows, _ = load_csv(path, header_row=2, encoding="utf-8")
    collect_master(rows, roster)
    return roster


def db_user(user_id: int, role: str, phone: str = "", *, name: str = "Somebody",
            password: str = "CSV_ONBOARDED", state_user_id=None,
            pii: PiiCrypto = None) -> dict:
    """The shape load_live_users_by_roles produces, without a database."""
    pii = pii or _pii()
    return {
        "id": user_id,
        "uuid": f"uuid-{user_id}",
        "name": name,
        "phone": phone,
        "phone_hash": pii.hmac(phone) if phone else "",
        "email": f"so_{phone}@pump-operator.local",
        "status": 1,
        "has_managed_password": has_managed_password(password),
        "state_user_id": state_user_id,
        "role": role,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Role selection
# ─────────────────────────────────────────────────────────────────────────────

class TestParseRoles:
    @pytest.mark.parametrize("value,expected", [
        ("so", "SECTION_OFFICER"),
        ("SO", "SECTION_OFFICER"),
        ("section-officer", "SECTION_OFFICER"),
        ("SECTION_OFFICER", "SECTION_OFFICER"),
        ("sdo", "SUB_DIVISIONAL_OFFICER"),
        ("SUB_DIVISIONAL_OFFICER", "SUB_DIVISIONAL_OFFICER"),
        ("ee", "EXECUTIVE_ENGINEER"),
        ("executive-engineer", "EXECUTIVE_ENGINEER"),
    ])
    def test_accepts_every_spelling_of_the_three_roles(self, value, expected):
        roles, rejected = parse_roles([value])

        assert roles == [expected]
        assert rejected == []

    def test_splits_on_commas_and_across_repeats(self):
        roles, rejected = parse_roles(["so,sdo", "ee"])

        assert roles == list(OFFBOARDABLE_ROLES)
        assert rejected == []

    def test_deduplicates_without_reordering(self):
        roles, _ = parse_roles(["sdo", "so", "section-officer", "sdo"])

        assert roles == ["SUB_DIVISIONAL_OFFICER", "SECTION_OFFICER"]

    def test_a_real_but_unoffboardable_role_is_skipped_with_a_reason(self):
        """A pump operator is a real role this tool must not touch — saying so is
        different from saying the value was not understood."""
        roles, rejected = parse_roles(["so", "jal-mitra"])

        assert roles == ["SECTION_OFFICER"]
        assert rejected[0]["value"] == "jal-mitra"
        assert rejected[0]["resolved_role"] == "PUMP_OPERATOR"
        assert "not offboardable" in rejected[0]["reason"]

    def test_an_administrative_role_never_enters_scope(self):
        roles, rejected = parse_roles(["state-admin", "super-user"])

        assert roles == []
        assert [r["value"] for r in rejected] == ["state-admin", "super-user"]

    def test_an_unknown_value_is_skipped_rather_than_invented(self):
        roles, rejected = parse_roles(["khalasi"])

        assert roles == []
        assert rejected[0]["resolved_role"] == ""
        assert "not a role this tool recognises" in rejected[0]["reason"]

    def test_blank_values_are_ignored_not_rejected(self):
        roles, rejected = parse_roles(["so,, ,"])

        assert roles == ["SECTION_OFFICER"]
        assert rejected == []


# ─────────────────────────────────────────────────────────────────────────────
# Reading the sheets
# ─────────────────────────────────────────────────────────────────────────────

class TestCollectMaster:
    def test_every_row_with_a_usable_phone_vouches_for_somebody(self, tmp_path):
        roster = master_roster(
            tmp_path,
            "USR-1,Debojit Patir,8638029838,sdo",
            "USR-2,Ashif Ahmed,7002921268,section-officer",
        )

        assert roster.phone_sources == {
            "918638029838": [MASTER_SOURCE],
            "917002921268": [MASTER_SOURCE],
        }
        assert roster.public_id_sources == {
            "usr-1": [MASTER_SOURCE], "usr-2": [MASTER_SOURCE],
        }

    def test_a_role_the_ingestion_never_onboards_still_names_a_person(self, tmp_path):
        """Presence in the master is presence. The ingestion skips a khalasi; that
        is not a reason to delete the account we hold for them."""
        roster = master_roster(tmp_path, "USR-3,Some Khalasi,9000000003,khalasi")

        assert "919000000003" in roster.phone_sources

    def test_a_row_the_ingestion_would_reject_still_protects(self, tmp_path):
        """A blank name blocks an INSERT, not an identity."""
        roster = master_roster(tmp_path, "USR-4,,9000000004,sdo")

        assert "919000000004" in roster.phone_sources

    def test_an_unusable_phone_is_reported_without_echoing_the_number(self, tmp_path):
        roster = master_roster(tmp_path, "USR-5,Bad Number,1234567890,sdo")

        assert roster.phone_sources == {}
        assert roster.issues[0]["source"] == MASTER_SOURCE
        assert roster.issues[0]["row_no"] == 3
        assert not any("1234567890" in i["issue"] for i in roster.issues)


class TestLoadProtectCsv:
    def test_finds_the_phone_column_whatever_the_sheet_calls_it(self, tmp_path):
        roster = Roster()
        path = write_csv(
            tmp_path, "so-map.csv", SO_MAPPING_HEADER,
            "SCH-001,8156128,USR-100,Ashif Ahmed,7002921268",
        )

        load_protect_csv(path, "so-map", 2, "utf-8", roster)

        assert roster.phone_sources == {"917002921268": ["so-map"]}
        assert roster.public_id_sources == {"usr-100": ["so-map"]}

    def test_reads_the_subdivision_sheets_misspelt_id_column(self, tmp_path):
        roster = Roster()
        path = write_csv(
            tmp_path, "sdo-map.csv", SDO_MAPPING_HEADER,
            "SDV-028,Bihpuria,USR-016067,Pritam Singh,7002506100",
        )

        load_protect_csv(path, "sdo-map", 2, "utf-8", roster)

        assert roster.public_id_sources == {"usr-016067": ["sdo-map"]}

    def test_ignores_public_ids_that_identify_a_scheme_or_a_location(self, tmp_path):
        """scheme_public_id and subdivision_public_id are not people, and letting
        one into the roster would spare a user who happens to share its text."""
        roster = Roster()
        path = write_csv(
            tmp_path, "so-map.csv", SO_MAPPING_HEADER,
            "SCH-001001,8156128,USR-100,Ashif Ahmed,7002921268",
        )

        load_protect_csv(path, "so-map", 2, "utf-8", roster)

        assert "sch-001001" not in roster.public_id_sources
        assert "8156128" not in roster.public_id_sources

    def test_one_phone_named_by_two_sheets_records_both(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Ashif Ahmed,7002921268,section-officer")
        path = write_csv(
            tmp_path, "so-map.csv", SO_MAPPING_HEADER,
            "SCH-001,8156128,USR-1,Ashif Ahmed,7002921268",
        )

        load_protect_csv(path, "so-map", 2, "utf-8", roster)

        assert roster.phone_sources["917002921268"] == [MASTER_SOURCE, "so-map"]
        # The healthy case: this sheet names nobody the master left out.
        assert roster.stats[1]["distinct_phones"] == 1
        assert roster.stats[1]["phones_no_earlier_sheet_had"] == 0

    def test_repeated_rows_collapse_to_one_identity(self, tmp_path):
        """The section-officer sheet is one row per scheme: 31k rows, a few
        hundred officers."""
        roster = Roster()
        path = write_csv(
            tmp_path, "so-map.csv", SO_MAPPING_HEADER,
            "SCH-001,1,USR-100,Ashif Ahmed,7002921268",
            "SCH-002,2,USR-100,Ashif Ahmed,7002921268",
            "SCH-003,3,USR-100,Ashif Ahmed,7002921268",
        )

        load_protect_csv(path, "so-map", 2, "utf-8", roster)

        assert list(roster.phone_sources) == ["917002921268"]
        assert roster.stats[0]["rows"] == 3
        assert roster.stats[0]["rows_with_a_usable_phone"] == 3
        assert roster.stats[0]["distinct_phones"] == 1

    def test_a_sheet_without_a_phone_column_is_refused(self, tmp_path):
        """Reading it as protecting nobody is indistinguishable from the file
        being wrong, and would delete everyone it names."""
        roster = Roster()
        path = write_csv(tmp_path, "no-phone.csv", "title,,\na,b,c\n", "1,2,3")

        with pytest.raises(SystemExit, match="no phone column"):
            load_protect_csv(path, "no-phone", 2, "utf-8", roster)


class TestResolveProtectCsvs:
    def test_the_three_mapping_sheets_are_read_by_default(self):
        resolved = resolve_protect_csvs([], use_defaults=True)

        assert len(resolved) == len(DEFAULT_PROTECT_CSVS)
        assert {label for _, label in resolved} == {
            "subdivision-sdo-mapping",
            "section-officer-scheme-mapping",
            "divsion-executive-engineer-mapping",
        }
        assert all(os.path.isfile(path) for path, _ in resolved)

    def test_defaults_can_be_turned_off_deliberately(self):
        assert resolve_protect_csvs([], use_defaults=False) == []

    def test_an_extra_sheet_is_appended(self, tmp_path):
        path = write_csv(tmp_path, "extra.csv", SO_MAPPING_HEADER)

        resolved = resolve_protect_csvs([path], use_defaults=False)

        assert resolved == [(path, "extra")]

    def test_a_missing_sheet_aborts_rather_than_silently_protecting_nobody(self):
        with pytest.raises(SystemExit, match="does not exist"):
            resolve_protect_csvs(["/nope/not-here.csv"], use_defaults=False)


# ─────────────────────────────────────────────────────────────────────────────
# The sparing contract
# ─────────────────────────────────────────────────────────────────────────────

class TestClassifyUsers:
    def test_a_user_no_sheet_names_is_deleted(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Still Here,9000000001,sdo")
        users = [db_user(10, "SECTION_OFFICER", "919000000099")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_ABSENT
        assert decisions[0].will_delete

    def test_the_master_spares_whatever_role_it_gives_them(self, tmp_path):
        """A DB section officer the master lists as a jal-mitra is a role change
        for the ingestion to reconcile, not a person to delete."""
        roster = master_roster(tmp_path, "USR-1,Ashif Ahmed,9000000001,jal-mitra")
        users = [db_user(10, "SECTION_OFFICER", "919000000001")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_IN_MASTER
        assert decisions[0].matched_sources == [MASTER_SOURCE]

    def test_a_mapping_sheet_alone_spares_a_user(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000002,sdo")
        path = write_csv(
            tmp_path, "so-map.csv", SO_MAPPING_HEADER,
            "SCH-001,1,USR-9,In Service,9000000001",
        )
        load_protect_csv(path, "so-map", 2, "utf-8", roster)
        users = [db_user(10, "SECTION_OFFICER", "919000000001")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_IN_PROTECT
        assert decisions[0].matched_sources == ["so-map"]

    def test_a_logged_in_account_is_never_deleted_by_a_sheet(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000002,sdo")
        users = [db_user(10, "EXECUTIVE_ENGINEER", "919000000001",
                         password="k5cmVhbCBtYW5hZ2VkIHNlY3JldA==")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_HAS_LOGIN
        assert not decisions[0].will_delete

    @pytest.mark.parametrize("password", [None, "", "CSV_ONBOARDED", "KEYCLOAK_MANAGED"])
    def test_placeholder_passwords_do_not_count_as_a_login(self, password):
        assert has_managed_password(password) is False

    def test_a_user_without_a_phone_hash_is_out_of_reach(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000002,sdo")
        users = [db_user(10, "SECTION_OFFICER", "")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_NO_PHONE

    def test_the_actor_is_never_deleted_by_their_own_run(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000002,sdo")
        users = [db_user(ACTOR_ID, "SECTION_OFFICER", "919000000001")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_ACTOR

    def test_being_named_by_a_sheet_outranks_every_other_reason(self, tmp_path):
        """The actor and a logged-in account are both spared anyway; what matters
        is that the report says WHY, and 'a sheet names them' is the true reason."""
        roster = master_roster(tmp_path, "USR-1,The Actor,9000000001,sdo")
        users = [db_user(ACTOR_ID, "SUB_DIVISIONAL_OFFICER", "919000000001",
                         password="an-encrypted-secret")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_IN_MASTER

    def test_a_state_id_a_sheet_still_names_is_flagged_but_not_decisive(self, tmp_path):
        """The phone is the identity. A sheet naming this person's state id
        against a different number is a warning, not a reprieve."""
        roster = master_roster(tmp_path, "USR-77,Changed Number,9000000002,sdo")
        users = [db_user(10, "SUB_DIVISIONAL_OFFICER", "919000000001",
                         state_user_id="USR-77")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].category == CAT_ABSENT
        assert decisions[0].public_id_sources == [MASTER_SOURCE]

    def test_a_state_id_match_is_not_reported_when_the_phone_matched(self, tmp_path):
        roster = master_roster(tmp_path, "USR-77,Same Person,9000000001,sdo")
        users = [db_user(10, "SUB_DIVISIONAL_OFFICER", "919000000001",
                         state_user_id="USR-77")]

        decisions = classify_users(users, roster, _pii(), ACTOR_ID)

        assert decisions[0].public_id_sources == []


class TestDeactivateOnlyPlan:
    """--deactivate-only changes the write, not the decision."""

    def _plans(self, tmp_path) -> tuple[OffboardPlan, OffboardPlan]:
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,sdo")
        users = [
            db_user(10, "SUB_DIVISIONAL_OFFICER", "919000000001"),
            db_user(11, "SUB_DIVISIONAL_OFFICER", "919000000002"),
        ]
        decisions = classify_users(users, roster, _pii(), ACTOR_ID)
        common = dict(roles=["SUB_DIVISIONAL_OFFICER"], rejected_roles=[], roster=roster)
        return (
            OffboardPlan(decisions=decisions, **common),
            OffboardPlan(decisions=decisions, deactivate_only=True, **common),
        )

    def test_the_same_people_are_selected_either_way(self, tmp_path):
        deleting, deactivating = self._plans(tmp_path)

        assert [d.user["id"] for d in deleting.deletions] == [11]
        assert [d.user["id"] for d in deactivating.deletions] == [11]

    def test_the_report_says_which_write_it_is(self, tmp_path):
        deleting, deactivating = self._plans(tmp_path)

        assert deleting.verb == "soft delete"
        assert deactivating.verb == "deactivate"
        assert deactivating.action_for(CAT_ABSENT) == DEACTIVATE_ACTION
        # A spared user is spared identically in both modes.
        assert deactivating.action_for(CAT_IN_MASTER) == deleting.action_for(CAT_IN_MASTER)

    def test_the_ceiling_message_names_the_write(self, tmp_path):
        _, deactivating = self._plans(tmp_path)

        assert "deactivate 1 user(s)" in ceiling_breach(deactivating, 0)


class TestCeilingBreach:
    def _plan(self, tmp_path, deletions: int) -> OffboardPlan:
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,sdo")
        users = [
            db_user(20 + n, "SECTION_OFFICER", f"9190000001{n:02d}")
            for n in range(deletions)
        ]
        return OffboardPlan(
            decisions=classify_users(users, roster, _pii(), ACTOR_ID),
            roles=["SECTION_OFFICER"], rejected_roles=[], roster=roster,
        )

    def test_a_plan_under_the_ceiling_may_execute(self, tmp_path):
        assert ceiling_breach(self._plan(tmp_path, 2), 3) is None

    def test_a_plan_exactly_at_the_ceiling_may_execute(self, tmp_path):
        """The ceiling is what the operator authorised, not one less than it."""
        assert ceiling_breach(self._plan(tmp_path, 3), 3) is None

    def test_one_over_the_ceiling_is_refused_and_names_both_numbers(self, tmp_path):
        breach = ceiling_breach(self._plan(tmp_path, 4), 3)

        assert breach is not None
        assert "4 user(s)" in breach and "ceiling of 3" in breach

    def test_a_ceiling_of_zero_refuses_any_deletion(self, tmp_path):
        assert ceiling_breach(self._plan(tmp_path, 1), 0) is not None
        assert ceiling_breach(self._plan(tmp_path, 0), 0) is None


class TestRoleFrame:
    def test_reports_the_share_each_role_would_lose(self, tmp_path):
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,sdo")
        users = [
            db_user(10, "SUB_DIVISIONAL_OFFICER", "919000000001"),
            db_user(11, "SUB_DIVISIONAL_OFFICER", "919000000002"),
            db_user(12, "SECTION_OFFICER", "919000000003"),
        ]
        plan = OffboardPlan(
            decisions=classify_users(users, roster, _pii(), ACTOR_ID),
            roles=["SUB_DIVISIONAL_OFFICER", "SECTION_OFFICER"],
            rejected_roles=[], roster=roster,
        )

        rows = {r["role"]: r for r in build_role_frame(plan).to_dict("records")}

        assert rows["SUB_DIVISIONAL_OFFICER"]["affected"] == 1
        assert rows["SUB_DIVISIONAL_OFFICER"]["share_affected"] == "50.0%"
        assert rows["SUB_DIVISIONAL_OFFICER"]["action"] == "soft delete"
        assert rows["SECTION_OFFICER"]["affected"] == 1
        assert rows["SECTION_OFFICER"]["share_affected"] == "100.0%"


# ─────────────────────────────────────────────────────────────────────────────
# CLI guards — these must hold before any connection is attempted
# ─────────────────────────────────────────────────────────────────────────────

UNREACHABLE_DSN = "host=127.0.0.1 port=1 dbname=nope user=nope connect_timeout=1"


def _cli(tmp_path, *extra: str) -> list[str]:
    csv_path = write_csv(
        tmp_path, "users-master.csv", CSV_HEADER, "USR-1,Somebody,9000000001,sdo"
    )
    return [
        "--csv", csv_path, "--actor-id", str(ACTOR_ID),
        "--tenant-dsn", UNREACHABLE_DSN, "--skip-analytics",
        "--out", str(tmp_path / "out.xlsx"), *extra,
    ]


class TestCliGuards:
    @pytest.fixture(autouse=True)
    def pii_keys(self, monkeypatch):
        """Every guard here must fire before a connection is attempted, so the
        keys only have to be well-formed, not real."""
        monkeypatch.setenv("PII_ENCRYPTION_KEY", base64.b64encode(b"\x01" * 32).decode())
        monkeypatch.setenv("PII_HMAC_KEY", base64.b64encode(b"\x02" * 32).decode())

    def test_execute_without_a_ceiling_is_refused(self, tmp_path, caplog):
        code = main(_cli(tmp_path, "--roles", "so", "--execute"))

        assert code == 2
        assert "--max-deletions is required" in caplog.text

    def test_a_scope_of_nothing_offboardable_is_refused(self, tmp_path, caplog):
        code = main(_cli(tmp_path, "--roles", "jal-mitra,khalasi"))

        assert code == 2
        assert "No offboardable role was given" in caplog.text
        assert "PUMP_OPERATOR is a real role" in caplog.text

    def test_a_master_sheet_that_names_nobody_is_refused(self, tmp_path, caplog):
        """A mis-parsed sheet would otherwise read as 'nobody is employed'."""
        path = write_csv(tmp_path, "empty.csv", CSV_HEADER, "USR-1,Bad,123,sdo")
        code = main([
            "--csv", path, "--roles", "so", "--actor-id", str(ACTOR_ID),
            "--tenant-dsn", UNREACHABLE_DSN, "--skip-analytics",
            "--out", str(tmp_path / "out.xlsx"),
        ])

        assert code == 2
        assert "no usable phone number" in caplog.text

    def test_deactivating_still_needs_a_ceiling(self, tmp_path, caplog):
        """A reversible write is still a write against every officer in scope."""
        code = main(_cli(tmp_path, "--roles", "so", "--deactivate-only", "--execute"))

        assert code == 2
        assert "--max-deletions is required" in caplog.text

    def test_a_negative_ceiling_is_refused(self, tmp_path, caplog):
        code = main(_cli(tmp_path, "--roles", "so", "--execute", "--max-deletions", "-1"))

        assert code == 2
        assert "cannot be negative" in caplog.text


# ─────────────────────────────────────────────────────────────────────────────
# Database-backed fixtures
# ─────────────────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def conn():
    try:
        connection = psycopg2.connect(DSN)
    except psycopg2.OperationalError as exc:
        pytest.skip(f"no PostgreSQL at {DSN}: {exc}")
    connection.autocommit = False
    yield connection
    connection.close()


@pytest.fixture
def conn_ready(conn):
    """A throwaway schema inside a transaction that is never committed.

    Nothing here commits, so the rollback at teardown removes the schemas, the
    users and any role row a test created — PostgreSQL rolls DDL back like any
    other statement. That is deliberate: pointing JJM_TEST_DSN at a database
    that matters must not be able to destroy anything in it.
    """
    conn.rollback()  # clear a transaction a previous failure may have aborted
    with conn.cursor() as cur:
        cur.execute("CREATE SCHEMA IF NOT EXISTS common_schema")
        cur.execute(COMMON_DDL)
        # Additive: a real database already holds these, and their ids are read
        # back rather than assumed.
        cur.execute(
            "INSERT INTO common_schema.user_type_master_table (c_name) "
            "VALUES ('SECTION_OFFICER'), ('SUB_DIVISIONAL_OFFICER'), "
            "('EXECUTIVE_ENGINEER'), ('PUMP_OPERATOR'), ('STATE_ADMIN') "
            "ON CONFLICT (c_name) DO NOTHING"
        )
        cur.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
        cur.execute(f"CREATE SCHEMA {SCHEMA}")
        cur.execute(DDL.format(schema=SCHEMA))
        # The actor takes id 1 deliberately. Without them the schema's serial
        # would hand ACTOR_ID to the first user a test seeds, which is spared as
        # the run's own author — quietly turning a deletion test into a no-op
        # that still passes.
        cur.execute(f"""
            INSERT INTO {SCHEMA}.user_table
                (uuid, tenant_id, title, email, user_type, password, status)
            VALUES (gen_random_uuid()::text, %s, 'actor', 'actor@test.local',
                    (SELECT id FROM common_schema.user_type_master_table
                     WHERE c_name = 'STATE_ADMIN'), 'x', 1)
            RETURNING id
        """, (TENANT_ID,))
        assert cur.fetchone()[0] == ACTOR_ID
        cur.execute("DROP SCHEMA IF EXISTS analytics_schema CASCADE")
        cur.execute("CREATE SCHEMA analytics_schema")
        cur.execute(ANALYTICS_DDL)
        cur.execute(
            "INSERT INTO analytics_schema.dim_tenant_table "
            "(tenant_id, state_code, title, status) VALUES (%s, 'AS', 'Assam', 1)",
            (TENANT_ID,),
        )
    yield conn
    conn.rollback()


@pytest.fixture
def db(conn_ready):
    database = OffboardDb(conn_ready, SCHEMA, _pii())
    database.with_state_user_id = True
    return database


@pytest.fixture
def roles(db) -> dict[str, int]:
    return {name: row.id for name, row in db.load_user_types().items()}


@pytest.fixture
def writer(db):
    return OffboardWriter(db, TENANT_ID, ACTOR_ID)


@pytest.fixture
def analytics(conn_ready):
    return OffboardAnalyticsWriter(conn_ready, TENANT_ID)


def seed_user(db: OffboardDb, name: str, phone: str, user_type: int, *,
              password: str = "CSV_ONBOARDED", state_user_id=None,
              status: int = 1, deleted: bool = False) -> int:
    import uuid as uuid_mod
    with db.conn.cursor() as cur:
        cur.execute(f"""
            INSERT INTO {SCHEMA}.user_table
                (uuid, tenant_id, title, title_hash, email, user_type,
                 phone_number, phone_number_hash, state_user_id, password, status,
                 deleted_at)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,{'NOW()' if deleted else 'NULL'})
            RETURNING id
        """, (
            str(uuid_mod.uuid4()), TENANT_ID,
            db.pii.encrypt(name), db.pii.title_hash(name),
            f"seed_{phone or uuid_mod.uuid4()}@pump-operator.local", user_type,
            db.pii.encrypt(phone) if phone else None,
            db.pii.hmac(phone) if phone else None,
            state_user_id, password, status,
        ))
        return cur.fetchone()[0]


def seed_mapping(db: OffboardDb, user_id: int, scheme_id: int, deleted: bool = False) -> int:
    with db.conn.cursor() as cur:
        cur.execute(
            f"INSERT INTO {SCHEMA}.user_scheme_mapping_table "
            f"(user_id, scheme_id, status, deleted_at) "
            f"VALUES (%s,%s,1,{'NOW()' if deleted else 'NULL'}) RETURNING id",
            (user_id, scheme_id),
        )
        return cur.fetchone()[0]


def user_row(db: OffboardDb, user_id: int) -> tuple:
    with db.conn.cursor() as cur:
        cur.execute(
            f"SELECT status, deleted_at IS NOT NULL, deleted_by, updated_by "
            f"FROM {SCHEMA}.user_table WHERE id = %s", (user_id,)
        )
        return cur.fetchone()


def live_mappings(db: OffboardDb, user_id: int) -> set[int]:
    with db.conn.cursor() as cur:
        cur.execute(
            f"SELECT scheme_id FROM {SCHEMA}.user_scheme_mapping_table "
            f"WHERE user_id = %s AND deleted_at IS NULL", (user_id,)
        )
        return {row[0] for row in cur}


# ─────────────────────────────────────────────────────────────────────────────
# Reading the tenant
# ─────────────────────────────────────────────────────────────────────────────

class TestLoadLiveUsersByRoles:
    def test_reads_only_the_selected_roles(self, db, roles):
        so = seed_user(db, "Section Officer", "919000000001", roles["SECTION_OFFICER"])
        seed_user(db, "Pump Operator", "919000000002", roles["PUMP_OPERATOR"])
        seed_user(db, "State Admin", "919000000003", roles["STATE_ADMIN"])

        found = db.load_live_users_by_roles(["SECTION_OFFICER"])

        assert [u["id"] for u in found] == [so]
        assert found[0]["role"] == "SECTION_OFFICER"

    def test_skips_users_already_soft_deleted(self, db, roles):
        live = seed_user(db, "Live", "919000000001", roles["SECTION_OFFICER"])
        seed_user(db, "Gone", "919000000002", roles["SECTION_OFFICER"], deleted=True)

        found = db.load_live_users_by_roles(["SECTION_OFFICER"])

        assert [u["id"] for u in found] == [live]

    def test_decrypts_the_name_and_phone_and_judges_the_password(self, db, roles):
        uid = seed_user(db, "Ashif Ahmed", "919000000001", roles["SECTION_OFFICER"],
                        password="an-encrypted-managed-secret", state_user_id="USR-1")

        found = db.load_live_users_by_roles(["SECTION_OFFICER"])

        assert found[0]["id"] == uid
        assert found[0]["name"] == "Ashif Ahmed"
        assert found[0]["phone"] == "919000000001"
        assert found[0]["has_managed_password"] is True
        assert found[0]["state_user_id"] == "USR-1"
        # The secret itself must not travel with the record.
        assert "password" not in found[0]

    def test_an_empty_role_list_reads_nothing(self, db, roles):
        seed_user(db, "Section Officer", "919000000001", roles["SECTION_OFFICER"])

        assert db.load_live_users_by_roles([]) == []

    def test_counts_only_live_scheme_mappings(self, db, roles):
        uid = seed_user(db, "Section Officer", "919000000001", roles["SECTION_OFFICER"])
        seed_mapping(db, uid, 501)
        seed_mapping(db, uid, 502)
        seed_mapping(db, uid, 503, deleted=True)

        assert db.count_live_scheme_mappings([uid]) == {uid: 2}


class TestBuildPlanAgainstTheTenant:
    def test_spares_the_named_and_deletes_the_rest(self, db, roles, tmp_path):
        kept = seed_user(db, "Kept", "919000000001", roles["SECTION_OFFICER"])
        dropped = seed_user(db, "Dropped", "919000000002", roles["SECTION_OFFICER"])
        seed_mapping(db, dropped, 501)
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,section-officer")

        plan = build_plan(db, roster, ["SECTION_OFFICER"], [], ACTOR_ID)

        by_id = {d.user["id"]: d for d in plan.decisions}
        assert by_id[kept].category == CAT_IN_MASTER
        assert by_id[dropped].category == CAT_ABSENT
        assert by_id[dropped].live_mappings == 1
        assert [d.user["id"] for d in plan.deletions] == [dropped]


# ─────────────────────────────────────────────────────────────────────────────
# Write paths
# ─────────────────────────────────────────────────────────────────────────────

class TestSoftDeleteUsers:
    def test_writes_status_and_the_delete_stamp_together(self, db, writer, roles):
        """deleted_at alone would leave the account able to log in: the staff
        login path filters on status, not on deleted_at."""
        uid = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])

        assert writer.soft_delete_users([uid]) == 1

        status, deleted, deleted_by, updated_by = user_row(db, uid)
        assert status == USER_STATUS_INACTIVE
        assert deleted is True
        assert deleted_by == ACTOR_ID
        assert updated_by == ACTOR_ID

    def test_leaves_everybody_else_alone(self, db, writer, roles):
        dropped = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])
        kept = seed_user(db, "Kept", "919000000002", roles["SECTION_OFFICER"])

        writer.soft_delete_users([dropped])

        assert user_row(db, kept) == (1, False, None, None)

    def test_a_user_already_deleted_is_not_touched_again(self, db, writer, roles):
        uid = seed_user(db, "Gone", "919000000001", roles["SECTION_OFFICER"],
                        deleted=True)

        assert writer.soft_delete_users([uid]) == 0

    def test_an_empty_batch_writes_nothing(self, db, writer):
        assert writer.soft_delete_users([]) == 0

    def test_deduplicates_ids_rather_than_double_counting(self, db, writer, roles):
        uid = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])

        assert writer.soft_delete_users([uid, uid]) == 1


class TestSoftDeleteSchemeMappings:
    def test_removes_every_live_mapping_of_the_deleted_users(self, db, writer, roles):
        uid = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])
        seed_mapping(db, uid, 501)
        seed_mapping(db, uid, 502)

        assert writer.soft_delete_scheme_mappings([uid]) == 2
        assert live_mappings(db, uid) == set()

    def test_does_not_touch_another_users_mappings(self, db, writer, roles):
        dropped = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])
        kept = seed_user(db, "Kept", "919000000002", roles["SECTION_OFFICER"])
        seed_mapping(db, dropped, 501)
        seed_mapping(db, kept, 501)

        writer.soft_delete_scheme_mappings([dropped])

        assert live_mappings(db, kept) == {501}

    def test_an_already_deleted_mapping_is_not_restamped(self, db, writer, roles):
        uid = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])
        seed_mapping(db, uid, 501, deleted=True)

        assert writer.soft_delete_scheme_mappings([uid]) == 0

    def test_records_who_dropped_it(self, db, writer, roles):
        uid = seed_user(db, "Dropped", "919000000001", roles["SECTION_OFFICER"])
        mapping_id = seed_mapping(db, uid, 501)

        writer.soft_delete_scheme_mappings([uid])

        with db.conn.cursor() as cur:
            cur.execute(
                f"SELECT deleted_by, updated_by FROM {SCHEMA}.user_scheme_mapping_table "
                f"WHERE id = %s", (mapping_id,)
            )
            assert cur.fetchone() == (ACTOR_ID, ACTOR_ID)


class TestDeactivateUsers:
    def test_writes_status_and_no_deletion_stamp(self, db, writer, roles):
        uid = seed_user(db, "Left", "919000000001", roles["SECTION_OFFICER"])

        assert writer.deactivate_users([uid]) == 1

        status, deleted, deleted_by, updated_by = user_row(db, uid)
        assert status == USER_STATUS_INACTIVE
        assert deleted is False
        assert deleted_by is None
        assert updated_by == ACTOR_ID

    def test_leaves_the_scheme_mappings_where_they_are(self, db, writer, roles):
        """A reactivated officer who came back without their schemes would be
        worse off than one who never left."""
        uid = seed_user(db, "Left", "919000000001", roles["SECTION_OFFICER"])
        seed_mapping(db, uid, 501)

        writer.deactivate_users([uid])

        assert live_mappings(db, uid) == {501}

    def test_a_user_already_inactive_is_not_restamped(self, db, writer, roles):
        uid = seed_user(db, "Already Off", "919000000001", roles["SECTION_OFFICER"],
                        status=USER_STATUS_INACTIVE)

        assert writer.deactivate_users([uid]) == 0

    def test_a_soft_deleted_user_is_left_alone(self, db, writer, roles):
        uid = seed_user(db, "Gone", "919000000001", roles["SECTION_OFFICER"],
                        deleted=True)

        assert writer.deactivate_users([uid]) == 0

    def test_leaves_everybody_else_alone(self, db, writer, roles):
        left = seed_user(db, "Left", "919000000001", roles["SECTION_OFFICER"])
        kept = seed_user(db, "Kept", "919000000002", roles["SECTION_OFFICER"])

        writer.deactivate_users([left])

        assert user_row(db, kept) == (1, False, None, None)

    def test_an_empty_batch_writes_nothing(self, db, writer):
        assert writer.deactivate_users([]) == 0


class TestExecuteTenantDeactivateOnly:
    def test_deactivates_and_deletes_nothing(self, db, writer, roles, tmp_path):
        kept = seed_user(db, "Kept", "919000000001", roles["SUB_DIVISIONAL_OFFICER"])
        left = seed_user(db, "Left", "919000000002", roles["SUB_DIVISIONAL_OFFICER"])
        seed_mapping(db, left, 502)
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,sdo")
        plan = build_plan(db, roster, ["SUB_DIVISIONAL_OFFICER"], [], ACTOR_ID,
                          deactivate_only=True)

        stats = execute_tenant(plan, writer)

        assert stats == {"users_deactivated": 1}
        assert user_row(db, left) == (USER_STATUS_INACTIVE, False, None, ACTOR_ID)
        assert live_mappings(db, left) == {502}
        assert user_row(db, kept) == (1, False, None, None)

    def test_the_warehouse_gets_the_status_but_keeps_the_mappings(
            self, db, analytics, roles, tmp_path):
        import uuid as uuid_mod
        left = seed_user(db, "Left", "919000000002", roles["SECTION_OFFICER"])
        with db.conn.cursor() as cur:
            cur.execute(
                "INSERT INTO analytics_schema.dim_user_table "
                "(user_id, tenant_id, status) VALUES (%s,%s,1)", (left, TENANT_ID),
            )
            cur.execute(
                "INSERT INTO analytics_schema.dim_user_scheme_mapping_table "
                "(uuid, user_id, scheme_id, status, tenant_id) VALUES (%s,%s,502,1,%s)",
                (str(uuid_mod.uuid4()), left, TENANT_ID),
            )
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000001,section-officer")
        plan = build_plan(db, roster, ["SECTION_OFFICER"], [], ACTOR_ID,
                          deactivate_only=True)

        assert [d.user["id"] for d in plan.deletions] == [left]
        stats = execute_analytics(plan, analytics)

        assert stats == {"dim_user_rows_deactivated": 1}
        with db.conn.cursor() as cur:
            cur.execute(
                "SELECT count(*) FROM analytics_schema.dim_user_scheme_mapping_table "
                "WHERE user_id = %s", (left,)
            )
            assert cur.fetchone() == (1,)


class TestExecuteTenant:
    def test_deletes_the_users_and_their_mappings_in_one_pass(
            self, db, writer, roles, tmp_path):
        kept = seed_user(db, "Kept", "919000000001", roles["SUB_DIVISIONAL_OFFICER"])
        dropped = seed_user(db, "Dropped", "919000000002", roles["SUB_DIVISIONAL_OFFICER"])
        seed_mapping(db, kept, 501)
        seed_mapping(db, dropped, 502)
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,sdo")
        plan = build_plan(db, roster, ["SUB_DIVISIONAL_OFFICER"], [], ACTOR_ID)

        stats = execute_tenant(plan, writer)

        assert stats == {"users_soft_deleted": 1, "scheme_mappings_soft_deleted": 1}
        assert user_row(db, dropped)[1] is True
        assert user_row(db, kept)[1] is False
        assert live_mappings(db, kept) == {501}

    def test_a_protected_user_survives_execution(self, db, writer, roles, tmp_path):
        logged_in = seed_user(db, "Logged In", "919000000002",
                              roles["EXECUTIVE_ENGINEER"],
                              password="an-encrypted-managed-secret")
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000001,ee")
        plan = build_plan(db, roster, ["EXECUTIVE_ENGINEER"], [], ACTOR_ID)

        assert plan.by_category()[CAT_HAS_LOGIN][0].user["id"] == logged_in
        execute_tenant(plan, writer)

        assert user_row(db, logged_in) == (1, False, None, None)


class TestExecuteAnalytics:
    def _seed_dim(self, conn, user_id: int, scheme_ids=()) -> None:
        import uuid as uuid_mod
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO analytics_schema.dim_user_table "
                "(user_id, tenant_id, email, user_type, title, status) "
                "VALUES (%s,%s,%s,1,%s,1)",
                (user_id, TENANT_ID, f"u{user_id}@x.local", f"User {user_id}"),
            )
            for scheme_id in scheme_ids:
                cur.execute(
                    "INSERT INTO analytics_schema.dim_user_scheme_mapping_table "
                    "(uuid, user_id, scheme_id, status, tenant_id) "
                    "VALUES (%s,%s,%s,1,%s)",
                    (str(uuid_mod.uuid4()), user_id, scheme_id, TENANT_ID),
                )

    def test_the_warehouse_ends_up_matching_the_tenant(
            self, db, analytics, roles, tmp_path):
        kept = seed_user(db, "Kept", "919000000001", roles["SECTION_OFFICER"])
        dropped = seed_user(db, "Dropped", "919000000002", roles["SECTION_OFFICER"])
        self._seed_dim(db.conn, kept, [501])
        self._seed_dim(db.conn, dropped, [502, 503])
        roster = master_roster(tmp_path, "USR-1,Kept,9000000001,section-officer")
        plan = build_plan(db, roster, ["SECTION_OFFICER"], [], ACTOR_ID)

        stats = execute_analytics(plan, analytics)

        assert stats == {
            "dim_user_rows_deactivated": 1,
            "dim_user_scheme_mapping_rows_removed": 2,
        }
        with db.conn.cursor() as cur:
            cur.execute(
                "SELECT user_id, status FROM analytics_schema.dim_user_table "
                "ORDER BY user_id"
            )
            assert cur.fetchall() == [(kept, 1), (dropped, USER_STATUS_INACTIVE)]
            cur.execute(
                "SELECT user_id FROM analytics_schema.dim_user_scheme_mapping_table"
            )
            assert [row[0] for row in cur] == [kept]

    def test_another_tenants_rows_are_never_touched(self, db, analytics, roles, tmp_path):
        """dim_user_table.user_id is not unique across tenants — V32 dropped the
        PK — so every warehouse statement has to be tenant-scoped."""
        dropped = seed_user(db, "Dropped", "919000000002", roles["SECTION_OFFICER"])
        with db.conn.cursor() as cur:
            cur.execute(
                "INSERT INTO analytics_schema.dim_tenant_table "
                "(tenant_id, state_code, title, status) VALUES (99, 'MP', 'MP', 1)"
            )
            cur.execute(
                "INSERT INTO analytics_schema.dim_user_table "
                "(user_id, tenant_id, status) VALUES (%s, 99, 1)", (dropped,),
            )
        self._seed_dim(db.conn, dropped)
        roster = master_roster(tmp_path, "USR-1,Somebody Else,9000000001,section-officer")
        plan = build_plan(db, roster, ["SECTION_OFFICER"], [], ACTOR_ID)

        assert [d.user["id"] for d in plan.deletions] == [dropped]
        execute_analytics(plan, analytics)

        with db.conn.cursor() as cur:
            cur.execute(
                "SELECT status FROM analytics_schema.dim_user_table "
                "WHERE tenant_id = 99 AND user_id = %s", (dropped,)
            )
            assert cur.fetchone() == (1,)
